"""Data quality warning helpers for Streamlit pages."""

import json
import os
from typing import Any

import streamlit as st

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".."))
WARNINGS_PATH = os.path.join(ROOT, "data", "data_quality_warnings_20260228.json")


@st.cache_data
def load_data_quality_warnings() -> list[dict[str, Any]]:
    """Load pipeline-generated warning payloads."""
    if not os.path.exists(WARNINGS_PATH):
        return []
    with open(WARNINGS_PATH) as f:
        payload = json.load(f)
    return payload.get("warnings", [])


def render_data_quality_warnings() -> None:
    """Render warning banners generated by the data pipeline."""
    for warning in load_data_quality_warnings():
        title = warning.get("title", "Data quality warning")
        message = warning.get("message", "")
        action = warning.get("action", "")
        text = f"**{title}**\n\n{message}"
        if action:
            text += f"\n\n`{action}`"
        st.warning(text)
