"""Data quality warning helpers for Streamlit pages.

Rescued from `target260501` branch (commit f22e8bd, 2026-04-30) on
2026-06-01. The branch had this component wired into the legacy
`app/app.py` landing + `app/pages/4_hy_ig_methodology.py` page. Both
of those surfaces have been displaced by the multi-pair APP-PT1
template architecture (Waves 7–10), so the new home for this helper
is whichever Story / Methodology page template wants to surface
data-quality disclosures.

Behaviour: scans `data/data_quality_warnings_*.json` for any payload
file, loads the most recent by name, and renders each entry as a
Streamlit warning banner. Single producer (a data pipeline) emits the
JSON; any consumer can call ``render_data_quality_warnings()`` to
surface them.

Schema (per warning entry):
    id          : str    short stable identifier (e.g. "ice_bofa_oas_truncated")
    severity    : str    "warning" | "info" | "error" (Streamlit chrome)
    title       : str    short headline shown in bold
    message     : str    prose explanation
    action      : str    optional remediation command (rendered as code)
    artifact    : str    optional path to a follow-up artefact
"""

from __future__ import annotations

import glob
import json
import os
from typing import Any

import streamlit as st

_ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".."))
_WARNINGS_GLOB = os.path.join(_ROOT, "data", "data_quality_warnings_*.json")


@st.cache_data
def load_data_quality_warnings() -> list[dict[str, Any]]:
    """Load pipeline-generated warning payloads.

    Resolves to the most recent ``data/data_quality_warnings_<DATE>.json``
    by filename sort. Returns an empty list when no payload exists, so
    consumers can call unconditionally without guarding.
    """
    paths = sorted(glob.glob(_WARNINGS_GLOB))
    if not paths:
        return []
    with open(paths[-1]) as f:
        payload = json.load(f)
    return payload.get("warnings", [])


def render_data_quality_warnings() -> None:
    """Render warning banners generated by the data pipeline.

    Severity ``warning`` (default) renders as ``st.warning``; ``info`` and
    ``error`` map to ``st.info`` / ``st.error`` respectively. Unknown
    severities fall back to ``st.warning``.
    """
    severity_map = {
        "info": st.info,
        "warning": st.warning,
        "error": st.error,
    }
    for warning in load_data_quality_warnings():
        severity = warning.get("severity", "warning")
        title = warning.get("title", "Data quality warning")
        message = warning.get("message", "")
        action = warning.get("action", "")
        text = f"**{title}**\n\n{message}"
        if action:
            text += f"\n\n`{action}`"
        severity_map.get(severity, st.warning)(text)
