#!/usr/bin/env python3
"""
Chart Generation: University of Michigan Consumer Sentiment (UMCSENT) × XLV
=============================================================
Produces the standard 10-chart Plotly JSON set for the Streamlit portal.

Charts:
  1. umcsent_xlv_hero           -- UMCSENT YoY vs XLV price (dual-axis)
  2. umcsent_xlv_correlations   -- Pearson correlation heatmap
  3. umcsent_xlv_regime_stats   -- XLV returns by UMCSENT quartile
  4. umcsent_xlv_ccf            -- Cross-correlation function
  5. umcsent_xlv_equity_curves  -- Winner equity curve vs B&H
  6. umcsent_xlv_drawdown       -- Drawdown comparison
  7. umcsent_xlv_rolling_sharpe -- Rolling 12M Sharpe
  8. umcsent_xlv_tournament_scatter -- Sharpe vs MDD scatter
  9. umcsent_xlv_signal_dist    -- Signal distribution / direction breakdown
  10. umcsent_xlv_wf_sharpe     -- Walk-forward OOS rolling Sharpe
  11. correlation_scatter        -- UMCSENT YoY vs XLV 6M forward return cloud

Author: Econ Evan (Econometrics Agent)
Date: 2026-04-20
"""

import os
import json
import sys
import warnings
from datetime import datetime, timezone
from pathlib import Path
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

warnings.filterwarnings("ignore", category=FutureWarning)

BASE_DIR = str(Path(__file__).resolve().parents[1])
PAIR_ID = "umcsent_xlv"
DATE_TAG = "20260420"
EXPECTED_DIRECTION = "procyclical"
RESULTS_DIR = os.path.join(BASE_DIR, "results", PAIR_ID)
EXPLORE_DIR = os.path.join(RESULTS_DIR, f"exploratory_{DATE_TAG}")
MODELS_DIR = os.path.join(RESULTS_DIR, f"core_models_{DATE_TAG}")
DATA_DIR = os.path.join(BASE_DIR, "data")
CHART_DIR = os.path.join(BASE_DIR, "output", "charts", PAIR_ID, "plotly")
os.makedirs(CHART_DIR, exist_ok=True)

PALETTE_ID = "okabe_ito_2026"
PALETTE = json.loads(
    Path(BASE_DIR, "docs", "schemas", "color_palette_registry.json").read_text()
)["palettes"][PALETTE_ID]

# Color palette: docs/schemas/color_palette_registry.json :: okabe_ito_2026.
C_INDICATOR = PALETTE["primary_data_trace"]
C_EQUITY = PALETTE["secondary_data_trace"]
C_STRATEGY = PALETTE["equity_curve"]
C_BENCHMARK = PALETTE["benchmark_trace"]
C_SPY = PALETTE["tertiary_data_trace"]
C_CONTRACTION = "rgba(213,94,0,0.12)"
C_DD_FILL = PALETTE["drawdown_fill"]
C_NBER = PALETTE["nber_shading"]
NBER_RECESSIONS = [
    ("2001-03-01", "2001-11-30"),
    ("2007-12-01", "2009-06-30"),
    ("2020-02-01", "2020-04-30"),
]


def bullish_condition(signal, threshold):
    """Return the XLV-bullish condition implied by EXPECTED_DIRECTION."""
    if EXPECTED_DIRECTION == "procyclical":
        return signal > threshold
    if EXPECTED_DIRECTION in {"countercyclical", "counter_cyclical"}:
        return signal < threshold
    raise ValueError(f"Unsupported EXPECTED_DIRECTION: {EXPECTED_DIRECTION}")


def canonical_name(name):
    prefix = f"{PAIR_ID}_"
    return name[len(prefix):] if name.startswith(prefix) else name


def save_chart(fig, name, *, caption=None, rules=None, sources=None, alignment=None):
    name = canonical_name(name)
    path = os.path.join(CHART_DIR, f"{name}.json")
    fig.write_json(path)
    meta = {
        "chart_name": name,
        "pair_id": PAIR_ID,
        "palette_id": PALETTE_ID,
        "rules_applied": rules or ["VIZ-O1"],
        "caption": caption or (fig.layout.title.text if fig.layout.title else name),
        "narrative_alignment_note": alignment or "Regenerated by Viz Vera.",
        "disposition": "consumed",
        "source_artifacts": sources or [],
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": "Viz Vera - scripts/generate_charts_umcsent_xlv.py",
    }
    Path(CHART_DIR, f"{name}_meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    fig.write_image(os.path.join(CHART_DIR, f"_perceptual_check_{name}.png"), width=1200, height=600)
    print(f"  Saved: {name}.json")


def load_monthly():
    """Load the monthly dataset."""
    parquet_path = os.path.join(DATA_DIR, "umcsent_xlv_monthly_19980101_20251231.parquet")
    return pd.read_parquet(parquet_path)


def load_tournament():
    return pd.read_csv(os.path.join(RESULTS_DIR, f"tournament_results_{DATE_TAG}.csv"))


def load_winner():
    with open(os.path.join(RESULTS_DIR, "winner_summary.json")) as f:
        return json.load(f)


def load_strategy_returns():
    path = os.path.join(RESULTS_DIR, f"strategy_returns_{DATE_TAG}.csv")
    df = pd.read_csv(path, parse_dates=["date"]).set_index("date").sort_index()
    return df


def add_nber_bands(fig, name="NBER recession period"):
    """Add NBER recession shading plus one legend entry."""
    for start, end in NBER_RECESSIONS:
        fig.add_vrect(
            x0=start,
            x1=end,
            fillcolor=C_NBER,
            layer="below",
            line_width=0,
        )
    fig.add_trace(
        go.Scatter(
            x=[None],
            y=[None],
            mode="markers",
            marker=dict(size=12, color="rgba(120,120,120,0.35)", symbol="square"),
            name=name,
            hoverinfo="skip",
        )
    )


# ===================================================================
# CHART 1: Hero — UMCSENT YoY vs XLV price (dual-axis)
# ===================================================================
def chart_hero():
    df = load_monthly()

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    # UMCSENT YoY on primary axis
    yoy_valid = df["umcsent_yoy"].dropna()
    fig.add_trace(
        go.Scatter(x=yoy_valid.index, y=yoy_valid.values,
                   name="UMCSENT YoY Change (%)",
                   line=dict(color=C_INDICATOR, width=2)),
        secondary_y=False,
    )

    # XLV price on secondary axis
    fig.add_trace(
        go.Scatter(x=df.index, y=df["xlv"],
                   name="XLV Price ($)",
                   line=dict(color=C_EQUITY, width=1.5)),
        secondary_y=True,
    )

    # Shade periods when UMCSENT YoY < 0 (pessimism)
    if "umcsent_yoy" in df.columns:
        pessimism = df["umcsent_yoy"] < 0
        starts = pessimism.index[pessimism & ~pessimism.shift(1, fill_value=False)]
        ends = pessimism.index[pessimism & ~pessimism.shift(-1, fill_value=False)]
        for s, e in zip(starts, ends):
            fig.add_vrect(x0=s, x1=e, fillcolor=C_CONTRACTION,
                          layer="below", line_width=0)
        fig.add_trace(
            go.Scatter(
                x=[None],
                y=[None],
                mode="markers",
                marker=dict(size=12, color=C_CONTRACTION, symbol="square"),
                name="Falling UMCSENT YoY period",
                hoverinfo="skip",
            )
        )

    fig.add_hline(y=0, line_dash="dash", line_color="gray", line_width=0.5,
                  secondary_y=False)

    fig.update_layout(
        title="UMCSENT YoY Change vs XLV Price (1999-2025)",
        template="plotly_white",
        hovermode="x unified",
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
        height=500,
    )
    fig.update_yaxes(title_text="UMCSENT YoY Change (%)", secondary_y=False)
    fig.update_yaxes(title_text="XLV Price ($)", secondary_y=True)
    save_chart(fig, f"{PAIR_ID}_hero")


# ===================================================================
# CHART 1b: Correlation scatter cloud
# ===================================================================
def chart_correlation_scatter():
    df = load_monthly()
    valid = df[["umcsent_yoy", "xlv_fwd_6m"]].dropna()
    x = valid["umcsent_yoy"].astype(float)
    y = valid["xlv_fwd_6m"].astype(float) * 100

    slope, intercept = np.polyfit(x, y, 1)
    xs = np.linspace(float(x.min()), float(x.max()), 100)
    ys = slope * xs + intercept
    corr = float(np.corrcoef(x, y)[0, 1])

    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=x,
            y=y,
            mode="markers",
            name="Monthly observations",
            marker=dict(color=C_EQUITY, size=7, opacity=0.55),
            hovertemplate=(
                "UMCSENT YoY: %{x:.2f}%<br>"
                "XLV 6-month forward return: %{y:.2f}%<extra></extra>"
            ),
        )
    )
    fig.add_trace(
        go.Scatter(
            x=xs,
            y=ys,
            mode="lines",
            name=f"Linear fit (r={corr:.2f})",
            line=dict(color=C_INDICATOR, width=2),
            hoverinfo="skip",
        )
    )
    fig.add_vline(x=0, line_dash="dash", line_color="#444", line_width=1)
    fig.add_hline(y=0, line_dash="dash", line_color="#444", line_width=1)
    fig.update_layout(
        title="UMCSENT YoY vs XLV 6-Month Forward Returns",
        xaxis_title="UMCSENT YoY Change (%)",
        yaxis_title="XLV 6-Month Forward Return (%)",
        template="plotly_white",
        height=470,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    fig.add_annotation(
        text=(
            "The cloud slopes upward but remains wide, so linear correlation "
            "is useful as a summary but not sufficient as the only model."
        ),
        xref="paper",
        yref="paper",
        x=0,
        y=-0.2,
        showarrow=False,
        align="left",
        font=dict(size=11, color="#555"),
    )
    save_chart(fig, "correlation_scatter")


# ===================================================================
# CHART 2: Correlation heatmap
# ===================================================================
def chart_correlations():
    corr_df = pd.read_csv(os.path.join(EXPLORE_DIR, "correlations.csv"))
    pearson = corr_df[corr_df["method"] == "Pearson"]

    pivot = pearson.pivot(index="signal", columns="horizon", values="correlation")
    col_order = [c for c in ["xlv_fwd_1m", "xlv_fwd_3m", "xlv_fwd_6m", "xlv_fwd_12m"]
                 if c in pivot.columns]
    pivot = pivot[col_order]

    # Clean axis labels
    row_labels = [s.replace("umcsent_", "UMCSENT ").replace("_", " ") for s in pivot.index]
    col_labels = [c.replace("xlv_fwd_", "").upper() for c in pivot.columns]

    # Mark significance
    pivot_p = pearson.pivot(index="signal", columns="horizon", values="p_value")[col_order]
    annot = []
    for i, row in enumerate(pivot.index):
        r = []
        for j, col in enumerate(pivot.columns):
            val = pivot.loc[row, col]
            p = pivot_p.loc[row, col]
            star = "**" if p < 0.01 else ("*" if p < 0.05 else "")
            r.append(f"{val:.3f}{star}")
        annot.append(r)

    fig = go.Figure(data=go.Heatmap(
        z=pivot.values,
        x=col_labels,
        y=row_labels,
        colorscale="RdBu",
        zmid=0,
        zmin=-0.3, zmax=0.3,
        text=annot,
        texttemplate="%{text}",
        textfont={"size": 10},
    ))

    fig.update_layout(
        title="Pearson Correlation: UMCSENT Signals → XLV Forward Returns<br><sup>* p<0.05, ** p<0.01</sup>",
        xaxis_title="XLV Forward Return Horizon",
        yaxis_title="Signal",
        template="plotly_white",
        height=450,
    )
    save_chart(fig, f"{PAIR_ID}_correlations")


# ===================================================================
# CHART 3: Regime stats bar chart
# ===================================================================
def chart_regime_stats():
    regime_df = pd.read_csv(os.path.join(EXPLORE_DIR, "regime_descriptive_stats.csv"))

    colors = [C_INDICATOR, "#ff7f0e", C_EQUITY, C_STRATEGY]

    fig = make_subplots(rows=1, cols=2,
                        subplot_titles=["Annualized Sharpe by UMCSENT YoY Quartile",
                                        "Annualized Return by UMCSENT YoY Quartile"])

    fig.add_trace(go.Bar(
        x=regime_df["regime"], y=regime_df["sharpe"],
        name="Sharpe",
        marker_color=colors,
        text=[f"{v:.2f}" for v in regime_df["sharpe"]],
        textposition="outside",
    ), row=1, col=1)

    fig.add_trace(go.Bar(
        x=regime_df["regime"], y=regime_df["ann_return_pct"],
        name="Ann Return %",
        marker_color=colors,
        text=[f"{v:.1f}%" for v in regime_df["ann_return_pct"]],
        textposition="outside",
    ), row=1, col=2)

    fig.update_layout(
        template="plotly_white",
        height=450,
        showlegend=False,
    )
    fig.update_xaxes(title_text="Sentiment YoY Quartile (Q1=Low, Q4=High)")
    fig.update_yaxes(title_text="Annualized Sharpe", row=1, col=1)
    fig.update_yaxes(title_text="Annualized Return (%)", row=1, col=2)
    save_chart(fig, f"{PAIR_ID}_regime_stats")


# ===================================================================
# CHART 4: CCF bar chart
# ===================================================================
def chart_ccf():
    ccf_df = pd.read_csv(os.path.join(EXPLORE_DIR, "ccf.csv"))

    colors = [C_INDICATOR if sig else "#aec7e8" for sig in ccf_df["significant"]]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=ccf_df["lag"], y=ccf_df["ccf"],
        marker_color=colors,
        name="CCF",
    ))

    if len(ccf_df) > 0:
        se = ccf_df["se"].iloc[0]
        fig.add_hline(y=1.96 * se, line_dash="dash", line_color="gray", line_width=0.8,
                      annotation_text="95% CI")
        fig.add_hline(y=-1.96 * se, line_dash="dash", line_color="gray", line_width=0.8)

    fig.update_layout(
        title="Cross-Correlation: UMCSENT YoY Change vs XLV Monthly Return<br><sup>Red bars = statistically significant at 95%</sup>",
        xaxis_title="Lag (months; negative = UMCSENT leads XLV)",
        yaxis_title="Cross-Correlation",
        template="plotly_white",
        height=400,
    )
    save_chart(fig, f"{PAIR_ID}_ccf")


# ===================================================================
# Supplemental chart: Rolling Granger p-value + F-statistic
# ===================================================================
def chart_rolling_granger():
    rg = pd.read_csv(os.path.join(RESULTS_DIR, "rolling_granger_umcsent_xlv.csv"))
    rg["date"] = pd.to_datetime(rg["date"])
    fig = make_subplots(specs=[[{"secondary_y": True}]])
    fig.add_trace(
        go.Scatter(
            x=rg["date"],
            y=rg["p_value_24m"],
            name="Rolling p-value",
            mode="lines",
            line=dict(color=C_INDICATOR, width=2),
            hovertemplate="%{x|%Y-%m-%d}<br>p-value: %{y:.3f}<extra></extra>",
        ),
        secondary_y=False,
    )
    fig.add_trace(
        go.Scatter(
            x=rg["date"],
            y=rg["granger_f_24m"],
            name="Rolling F-statistic",
            mode="lines",
            line=dict(color=C_EQUITY, width=1.5, dash="dash"),
            hovertemplate="%{x|%Y-%m-%d}<br>F-statistic: %{y:.2f}<extra></extra>",
        ),
        secondary_y=True,
    )
    fig.add_hline(
        y=0.05,
        line_dash="dot",
        line_color="red",
        line_width=1.2,
        annotation_text="p = 0.05 significance line",
        annotation_position="bottom right",
        secondary_y=False,
    )
    fig.add_trace(
        go.Scatter(
            x=[rg["date"].min(), rg["date"].max()],
            y=[0.05, 0.05],
            name="p = 0.05 threshold",
            mode="lines",
            line=dict(color="red", width=1.2, dash="dot"),
            hoverinfo="skip",
        ),
        secondary_y=False,
    )
    add_nber_bands(fig)
    fig.update_layout(
        title="Rolling Granger Test: p-value and F-statistic",
        template="plotly_white",
        height=420,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    fig.update_xaxes(title_text="Date")
    fig.update_yaxes(title_text="p-value (lower is stronger evidence)", secondary_y=False)
    fig.update_yaxes(title_text="F-statistic", secondary_y=True)
    fig.add_annotation(
        text=(
            "The p-value is below 0.05 only in selected windows, not "
            "consistently across the sample."
        ),
        xref="paper",
        yref="paper",
        x=0,
        y=-0.22,
        showarrow=False,
        align="left",
        font=dict(size=11, color="#555"),
    )
    save_chart(fig, "rolling_granger")


# ===================================================================
# CHART 5: Equity curves (winner vs buy-and-hold)
# ===================================================================
def chart_equity_curves():
    winner = load_winner()
    strategy = load_strategy_returns()
    oos_start = winner["oos_period_start"]
    oos_end = winner["oos_period_end"]
    oos = strategy.loc[oos_start:oos_end].copy()

    fig = go.Figure()

    # Buy-and-hold XLV
    bh_cum = (1 + oos["bh_return"].fillna(0)).cumprod()
    fig.add_trace(go.Scatter(
        x=bh_cum.index, y=bh_cum.values,
        name="Buy & Hold XLV",
        line=dict(color=C_BENCHMARK, width=2, dash="dash"),
    ))

    strat_cum = (1 + oos["strategy_return"].fillna(0)).cumprod()
    fig.add_trace(go.Scatter(
        x=strat_cum.index, y=strat_cum.values,
        name="Winner: UMCSENT 3M momentum, z>1.0, 6M lead",
        line=dict(color=C_STRATEGY, width=2),
    ))
    add_nber_bands(fig)

    fig.update_layout(
        title=(
            "Equity Curves: Corrected UMCSENT Momentum Winner "
            f"(Sharpe {winner['oos_sharpe']:.2f}, {winner['oos_ann_return']:.2%} ann.)"
        ),
        xaxis_title="Date",
        yaxis_title="Cumulative Return ($1 invested)",
        template="plotly_white",
        height=500,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    save_chart(
        fig,
        "equity_curves",
        caption=(
            "Corrected winner uses UMCSENT 3-month momentum with a rolling z-score > 1.0 "
            f"threshold and 6-month lead; OOS Sharpe {winner['oos_sharpe']:.2f}, "
            f"annual return {winner['oos_ann_return']:.2%}. Shaded bands mark NBER recessions."
        ),
        rules=["ECON-SR1", "VIZ-NBER1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Winner-specific chart rebuilt from corrected strategy_returns, not reconstructed from tournament code.",
    )


# ===================================================================
# CHART 6: Drawdown comparison
# ===================================================================
def chart_drawdown():
    winner = load_winner()
    strategy = load_strategy_returns()
    oos = strategy.loc[winner["oos_period_start"]:winner["oos_period_end"]].copy()

    fig = go.Figure()

    # B&H drawdown
    bh_cum = (1 + oos["bh_return"].fillna(0)).cumprod()
    bh_dd = (bh_cum / bh_cum.cummax() - 1)
    fig.add_trace(go.Scatter(
        x=bh_dd.index, y=bh_dd.values * 100,
        name="Buy & Hold XLV",
        fill="tozeroy",
        fillcolor="rgba(108,122,137,0.15)",
        line=dict(color=C_BENCHMARK, width=1.5, dash="dash"),
    ))

    # Winner strategy drawdown
    strat_cum = (1 + oos["strategy_return"].fillna(0)).cumprod()
    strat_dd = (strat_cum / strat_cum.cummax() - 1)

    fig.add_trace(go.Scatter(
        x=strat_dd.index, y=strat_dd.values * 100,
        name="Winner: UMCSENT 3M momentum, z>1.0, 6M lead",
        fill="tozeroy",
        fillcolor=C_DD_FILL,
        line=dict(color=C_STRATEGY, width=2),
    ))
    add_nber_bands(fig)

    fig.update_layout(
        title=f"Drawdown Comparison: Corrected Winner Max DD {winner['oos_max_drawdown']:.1%}",
        xaxis_title="Date",
        yaxis_title="Drawdown (%)",
        template="plotly_white",
        height=400,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    save_chart(
        fig,
        "drawdown",
        caption=(
            f"Corrected strategy max drawdown is {winner['oos_max_drawdown']:.1%} "
            f"versus {winner['bh_max_drawdown']:.1%} for buy-and-hold XLV. "
            "Shaded bands mark NBER recessions."
        ),
        rules=["ECON-SR1", "VIZ-NBER1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Drawdown rebuilt from corrected canonical winner return series.",
    )


# ===================================================================
# CHART 7: Rolling Sharpe
# ===================================================================
def chart_rolling_sharpe():
    winner = load_winner()
    strategy = load_strategy_returns()
    oos = strategy.loc[winner["oos_period_start"]:winner["oos_period_end"]].copy()

    fig = go.Figure()

    # B&H rolling Sharpe (12M)
    bh_roll = oos["bh_return"].rolling(12, min_periods=8)
    bh_sharpe = (bh_roll.mean() / bh_roll.std()) * np.sqrt(12)
    fig.add_trace(go.Scatter(
        x=bh_sharpe.index, y=bh_sharpe.values,
        name="Buy & Hold XLV",
        line=dict(color=C_BENCHMARK, width=1.5, dash="dash"),
    ))

    # Winner strategy rolling Sharpe
    strat_roll = oos["strategy_return"].rolling(12, min_periods=8)
    strat_sharpe = (strat_roll.mean() / strat_roll.std()) * np.sqrt(12)
    fig.add_trace(go.Scatter(
        x=strat_sharpe.index, y=strat_sharpe.values,
        name="Winner: UMCSENT 3M momentum, z>1.0, 6M lead",
        line=dict(color=C_STRATEGY, width=2),
    ))
    add_nber_bands(fig)

    fig.add_hline(
        y=winner["oos_sharpe"],
        line_dash="dash",
        line_color=C_INDICATOR,
        line_width=1.2,
        annotation_text=f"Reported OOS Sharpe = {winner['oos_sharpe']:.2f}",
        annotation_position="top left",
    )
    fig.add_hline(y=0, line_dash="dash", line_color=C_BENCHMARK, line_width=0.5)

    fig.update_layout(
        title="Rolling 12-Month Sharpe: Corrected UMCSENT Momentum Winner",
        xaxis_title="Date",
        yaxis_title="Rolling Sharpe (12M)",
        template="plotly_white",
        height=400,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    save_chart(
        fig,
        "rolling_sharpe",
        caption=(
            f"Rolling 12-month Sharpe for corrected winner; full OOS Sharpe is "
            f"{winner['oos_sharpe']:.2f}. Shaded bands mark NBER recessions."
        ),
        rules=["ECON-SR1", "VIZ-NBER1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Winner-specific rolling Sharpe rebuilt from corrected canonical strategy returns.",
    )


# ===================================================================
# CHART 8: Tournament scatter (Sharpe vs MDD)
# ===================================================================
def chart_tournament_scatter():
    tourn_df = load_tournament()

    valid = tourn_df[(tourn_df["valid"]) & (tourn_df["signal"] != "BENCHMARK")]
    invalid = tourn_df[(~tourn_df["valid"]) & (tourn_df["signal"] != "BENCHMARK")]
    benchmark = tourn_df[tourn_df["signal"] == "BENCHMARK"]

    fig = go.Figure()

    if len(invalid) > 0:
        fig.add_trace(go.Scatter(
            x=invalid["annual_turnover"], y=invalid["oos_sharpe"],
            mode="markers",
            marker=dict(size=3, color="#cccccc", opacity=0.2),
            name="Invalid",
        ))

    if len(valid) > 0:
        dd_pct = valid["max_drawdown"] * 100
        fig.add_trace(go.Scatter(
            x=valid["annual_turnover"], y=valid["oos_sharpe"],
            mode="markers",
            marker=dict(
                size=5,
                color=dd_pct,
                colorscale="RdYlGn",
                colorbar=dict(title="Max DD (%)"),
                opacity=0.6,
            ),
            text=[f"{r['signal']}/{r['threshold']}/{r['strategy']}" for _, r in valid.iterrows()],
            hovertemplate="%{text}<br>Sharpe: %{y:.2f}<br>Turnover: %{x:.1f}<extra></extra>",
            name="Valid Strategies",
        ))

    if len(benchmark) > 0:
        fig.add_trace(go.Scatter(
            x=[benchmark.iloc[0]["annual_turnover"]],
            y=[benchmark.iloc[0]["oos_sharpe"]],
            mode="markers",
            marker=dict(size=14, color=C_BENCHMARK, symbol="diamond"),
            name="Buy-and-Hold XLV",
        ))

    top5 = valid.nlargest(5, "oos_sharpe") if len(valid) > 0 else pd.DataFrame()
    if len(top5) > 0:
        fig.add_trace(go.Scatter(
            x=top5["annual_turnover"], y=top5["oos_sharpe"],
            mode="markers",
            marker=dict(size=12, color=C_STRATEGY, symbol="star", line=dict(width=1, color="black")),
            name="Top 5",
        ))

    fig.update_layout(
        title=f"Tournament Results: {len(tourn_df):,} Combinations ({len(valid):,} Valid)",
        xaxis_title="Annual Turnover (trades/year)",
        yaxis_title="OOS Sharpe Ratio",
        template="plotly_white",
        height=500,
    )
    save_chart(fig, f"{PAIR_ID}_tournament_scatter")


# ===================================================================
# CHART 9: Signal distribution / direction breakdown
# ===================================================================
def chart_signal_dist():
    df = load_monthly()
    winner_data = load_winner()
    is_end = winner_data["is_end"]
    oos_start = winner_data["oos_start"]

    fig = make_subplots(
        rows=1,
        cols=2,
        subplot_titles=[
            "UMCSENT Year-over-Year Distribution",
            "XLV Returns: Rising vs Falling Sentiment",
        ],
    )

    yoy = df["umcsent_yoy"].dropna()

    # Histogram of YoY values
    fig.add_trace(go.Histogram(
        x=yoy.values,
        nbinsx=40,
        name="UMCSENT Year-over-Year",
        marker_color=C_INDICATOR,
        opacity=0.7,
    ), row=1, col=1)
    fig.add_vline(x=0, line_dash="dash", line_color="black", row=1, col=1)

    # XLV returns when sentiment is rising vs falling (direction signal)
    valid = df[["umcsent_direction", "xlv_fwd_3m"]].dropna()
    rising = valid.loc[valid["umcsent_direction"] > 0, "xlv_fwd_3m"] * 100
    falling = valid.loc[valid["umcsent_direction"] < 0, "xlv_fwd_3m"] * 100

    fig.add_trace(go.Box(
        y=rising.values,
        name=f"Rising Sentiment (n={len(rising)})",
        marker_color=C_SPY,
        boxmean=True,
        boxpoints=False,
        hovertemplate=(
            "Rising sentiment<br>"
            "3-month forward return: %{y:.2f}%<extra></extra>"
        ),
    ), row=1, col=2)
    fig.add_trace(go.Box(
        y=falling.values,
        name=f"Falling Sentiment (n={len(falling)})",
        marker_color=C_INDICATOR,
        boxmean=True,
        boxpoints=False,
        hovertemplate=(
            "Falling sentiment<br>"
            "3-month forward return: %{y:.2f}%<extra></extra>"
        ),
    ), row=1, col=2)

    fig.update_layout(
        template="plotly_white",
        height=450,
        showlegend=True,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    fig.update_xaxes(title_text="UMCSENT Year-over-Year (%)", row=1, col=1)
    fig.update_yaxes(title_text="Count", row=1, col=1)
    fig.update_yaxes(title_text="XLV 3-Month Forward Return (%)", row=1, col=2)
    fig.add_annotation(
        text=(
            "Box edges mark the first quartile and third quartile; whiskers "
            "show the standard box-plot range. Points beyond the whiskers "
            "are extreme observations, not confirmed data errors."
        ),
        xref="paper",
        yref="paper",
        x=0.5,
        y=-0.22,
        showarrow=False,
        align="center",
        font=dict(size=11, color="#555"),
    )
    save_chart(fig, "signal_dist")


# ===================================================================
# CHART 10: Walk-forward OOS rolling Sharpe
# ===================================================================
def chart_wf_sharpe():
    winner = load_winner()
    strategy = load_strategy_returns()
    oos = strategy.loc[winner["oos_period_start"]:winner["oos_period_end"]].copy()

    fig = go.Figure()

    # Annual Sharpe by calendar year
    years = sorted(oos.index.year.unique())
    annual_data = []
    for yr in years:
        yr_mask = oos.index.year == yr
        yr_ret = oos.loc[yr_mask, "strategy_return"].dropna()
        bh_ret = oos.loc[yr_mask, "bh_return"].dropna()
        if len(yr_ret) >= 8:
            s = (yr_ret.mean() / yr_ret.std()) * np.sqrt(12) if yr_ret.std() > 0 else 0
            b = (bh_ret.mean() / bh_ret.std()) * np.sqrt(12) if bh_ret.std() > 0 else 0
            annual_data.append({"year": yr, "strat_sharpe": s, "bh_sharpe": b})

    annual_df = pd.DataFrame(annual_data)
    if len(annual_df) > 0:
        bar_colors = [C_STRATEGY if v > 0 else C_INDICATOR for v in annual_df["strat_sharpe"]]
        fig.add_trace(go.Bar(
            x=annual_df["year"].astype(str),
            y=annual_df["strat_sharpe"],
            name="Strategy Annual Sharpe",
            marker_color=bar_colors,
        ))
        fig.add_trace(go.Scatter(
            x=annual_df["year"].astype(str),
            y=annual_df["bh_sharpe"],
            name="B&H XLV Sharpe",
            mode="lines+markers",
            line=dict(color=C_BENCHMARK, width=2, dash="dash"),
        ))

    fig.add_hline(
        y=winner["oos_sharpe"],
        line_dash="dash",
        line_color=C_INDICATOR,
        line_width=1.2,
        annotation_text=f"Full OOS Sharpe = {winner['oos_sharpe']:.2f}",
        annotation_position="top left",
    )
    fig.add_hline(y=0, line_dash="dash", line_color=C_BENCHMARK, line_width=0.5)

    fig.update_layout(
        title="Walk-Forward Annual Sharpe: Corrected UMCSENT Momentum Winner",
        xaxis_title="Year",
        yaxis_title="Annualized Sharpe Ratio",
        template="plotly_white",
        height=430,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
        barmode="group",
    )
    save_chart(
        fig,
        "wf_sharpe",
        caption=(
            "Calendar-year OOS Sharpe for the corrected winner against buy-and-hold XLV; "
            f"full-window OOS Sharpe is {winner['oos_sharpe']:.2f}."
        ),
        rules=["ECON-SR1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Winner-specific annual walk-forward Sharpe rebuilt from corrected strategy returns.",
    )


def refresh_strategy_dependent_csvs():
    winner = load_winner()
    df = load_strategy_returns()
    rows = []
    periods = [
        ("Dot-Com Crash", "2000-03-01", "2002-10-31", False),
        ("GFC", "2007-12-01", "2009-06-30", False),
        ("COVID", "2020-02-01", "2020-12-31", True),
        ("2022 Rates Shock", "2022-01-01", "2022-12-31", True),
        ("Full OOS", winner["oos_period_start"], winner["oos_period_end"], True),
    ]
    for name, start, end, is_oos in periods:
        seg = df.loc[start:end].copy()
        r = seg["strategy_return"].dropna()
        if len(r) == 0:
            ann_return = ann_vol = sharpe = max_dd = np.nan
        else:
            ann_return = r.mean() * 12
            ann_vol = r.std() * np.sqrt(12)
            sharpe = (r.mean() / r.std()) * np.sqrt(12) if r.std() > 0 else 0
            eq = (1 + r.fillna(0)).cumprod()
            max_dd = (eq / eq.cummax() - 1).min()
        rows.append({
            "period_name": name,
            "start_date": start,
            "end_date": end,
            "is_oos": is_oos,
            "ann_return": round(float(ann_return), 6) if pd.notna(ann_return) else np.nan,
            "ann_vol": round(float(ann_vol), 6) if pd.notna(ann_vol) else np.nan,
            "sharpe": round(float(sharpe), 6) if pd.notna(sharpe) else np.nan,
            "n_obs": int(len(r)),
            "max_drawdown": round(float(max_dd), 6) if pd.notna(max_dd) else np.nan,
        })
    pd.DataFrame(rows).to_csv(os.path.join(RESULTS_DIR, "subperiod_sharpe.csv"), index=False)

    rolling = df["strategy_return"].rolling(24, min_periods=16)
    out = pd.DataFrame({
        "date": df.index,
        "rolling_sharpe_24m": (rolling.mean() / rolling.std()) * np.sqrt(12),
    }).dropna()
    out.to_csv(os.path.join(RESULTS_DIR, "rolling_sharpe_umcsent_xlv.csv"), index=False)
    print("  Refreshed: subperiod_sharpe.csv, rolling_sharpe_umcsent_xlv.csv")


def chart_subperiod_sharpe():
    rows = pd.read_csv(os.path.join(RESULTS_DIR, "subperiod_sharpe.csv"))
    winner = load_winner()
    labels = [
        f"{r.period_name} ({'OOS' if r.is_oos else 'IS'})"
        for r in rows.itertuples(index=False)
    ]
    values = rows["sharpe"].astype(float)
    colors = [C_STRATEGY if v >= 0 else C_INDICATOR for v in values]
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=labels,
        y=values,
        marker_color=colors,
        text=[f"{v:+.2f}" for v in values],
        textposition="outside",
        name="Annualized Sharpe by episode",
    ))
    fig.add_hline(y=0, line_dash="dot", line_color=C_BENCHMARK, line_width=0.8)
    fig.update_layout(
        title="Sub-Period Sharpe: Corrected UMCSENT Momentum Winner",
        xaxis_title="Historical episode",
        yaxis_title="Annualized Sharpe Ratio",
        template="plotly_white",
        height=430,
        showlegend=False,
        margin=dict(b=120),
    )
    save_chart(
        fig,
        "subperiod_sharpe",
        caption=(
            "Sharpe by historical episode recomputed from corrected strategy_returns; "
            f"full OOS Sharpe is {winner['oos_sharpe']:.2f}."
        ),
        rules=["ECON-SR1", "ECON-CP1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/subperiod_sharpe.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Winner-specific subperiod chart rebuilt from corrected strategy returns.",
    )


def chart_rolling_sharpe_cp():
    winner = load_winner()
    rg = pd.read_csv(os.path.join(RESULTS_DIR, "rolling_sharpe_umcsent_xlv.csv"))
    rg["date"] = pd.to_datetime(rg["date"])
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=rg["date"],
        y=rg["rolling_sharpe_24m"],
        name="Rolling 24M Sharpe",
        mode="lines",
        line=dict(color=C_STRATEGY, width=2),
    ))
    add_nber_bands(fig)
    fig.add_hline(
        y=winner["oos_sharpe"],
        line_dash="dash",
        line_color=C_INDICATOR,
        line_width=1.2,
        annotation_text=f"Reported OOS Sharpe = {winner['oos_sharpe']:.2f}",
        annotation_position="top left",
    )
    fig.add_hline(y=0, line_dash="dot", line_color=C_BENCHMARK, line_width=0.8)
    fig.update_layout(
        title="Rolling 24-Month Strategy Sharpe: Corrected UMCSENT Momentum Winner",
        xaxis_title="Date",
        yaxis_title="Annualized Sharpe Ratio",
        template="plotly_white",
        height=420,
        legend=dict(orientation="v", x=1.08, xanchor="left", y=1, yanchor="top"),
    )
    save_chart(
        fig,
        "rolling_sharpe_cp",
        caption=(
            "Rolling 24-month Sharpe recomputed from corrected strategy_returns; "
            f"reported full OOS Sharpe is {winner['oos_sharpe']:.2f}. "
            "Shaded bands mark NBER recessions."
        ),
        rules=["ECON-SR1", "ECON-CP2", "VIZ-NBER1", "VIZ-O1", "VIZ-V5"],
        sources=[
            f"results/{PAIR_ID}/strategy_returns_{DATE_TAG}.csv",
            f"results/{PAIR_ID}/rolling_sharpe_umcsent_xlv.csv",
            f"results/{PAIR_ID}/winner_summary.json",
        ],
        alignment="Winner-specific rolling CP Sharpe rebuilt from corrected strategy returns.",
    )


# ===================================================================
# MAIN
# ===================================================================
if __name__ == "__main__":
    print(f"Generating charts for {PAIR_ID}...")
    if "--winner-refresh" in sys.argv:
        refresh_strategy_dependent_csvs()
        chart_equity_curves()
        chart_drawdown()
        chart_rolling_sharpe()
        chart_wf_sharpe()
        chart_subperiod_sharpe()
        chart_rolling_sharpe_cp()
        print("\nWinner-specific refresh complete.")
        raise SystemExit(0)

    chart_hero()
    chart_correlation_scatter()
    chart_correlations()
    chart_regime_stats()
    chart_ccf()
    chart_equity_curves()
    chart_drawdown()
    chart_rolling_sharpe()
    chart_tournament_scatter()
    chart_signal_dist()
    chart_wf_sharpe()
    chart_rolling_granger()
    print(f"\nDone. Charts saved to {CHART_DIR}")
    charts = os.listdir(CHART_DIR)
    print(f"Total charts: {len(charts)}")
    for c in sorted(charts):
        size_kb = os.path.getsize(os.path.join(CHART_DIR, c)) // 1024
        print(f"  {c}  ({size_kb} KB)")
