#!/usr/bin/env python3
"""permit_spy — performance-tab charts (equity_curves, drawdown, walk_forward).

Designed to plug the gap left by the original Wave 10I.A run, which never
generated these three chart JSONs for permit_spy. Reads:

  - results/permit_spy/winner_trade_log.csv  (regenerated by
    scripts/regen_permit_trade_log.py — the Option-B trade log)
  - data/permit_spy_monthly_<latest>.parquet (rebuilt master parquet)

Writes (under output/charts/permit_spy/plotly/):
  - equity_curves.json
  - drawdown.json
  - walk_forward.json

Chart conventions
-----------------
- Full-sample coverage (1993-02-28 to 2025-12-31). The OOS boundary
  (2018-01-01) is annotated with a vertical line + label so the user can
  read both the long-run picture and the OOS-only window the leaderboard
  reports against.
- The strategy curve is built from trade-log direction × SPY monthly
  returns — no re-replay of the tournament's strategy logic. The trade
  log is the source of truth on this page.

Usage
-----
    python3 scripts/generate_charts_permit_performance.py
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go

REPO_ROOT = Path(__file__).resolve().parents[1]
PAIR_ID = "permit_spy"
PAIR_DIR = REPO_ROOT / "results" / PAIR_ID
DATA_DIR = REPO_ROOT / "data"
CHART_DIR = REPO_ROOT / "output" / "charts" / PAIR_ID / "plotly"
CHART_DIR.mkdir(parents=True, exist_ok=True)

OOS_START = pd.Timestamp("2018-01-01")

# MQR-aligned palette (CLAUDE.md)
C_STRATEGY = "#0066A5"   # dark blue — primary line (strategy)
C_BENCHMARK = "#9E9FA1"  # grey — buy-and-hold reference
C_DRAWDOWN = "#D85427"   # red — drawdown shading
C_BENCH_DD = "#C0C1C2"   # light grey — benchmark drawdown
C_OOS_LINE = "#FFB945"   # orange — OOS boundary marker


def _load_trade_log() -> pd.DataFrame:
    log = pd.read_csv(PAIR_DIR / "winner_trade_log.csv")
    log["entry_date"] = pd.to_datetime(log["entry_date"])
    log["exit_date"] = pd.to_datetime(log["exit_date"])
    return log


def _load_master_monthly() -> pd.DataFrame:
    candidates = sorted(DATA_DIR.glob(f"{PAIR_ID}_monthly_*.parquet"))
    if not candidates:
        raise FileNotFoundError(
            f"No master parquet at {DATA_DIR}/{PAIR_ID}_monthly_*.parquet."
        )
    df = pd.read_parquet(candidates[-1])
    df.index = pd.DatetimeIndex(df.index)
    return df


def _build_strategy_position(log: pd.DataFrame, idx: pd.DatetimeIndex) -> pd.Series:
    """Step-function position series across the full monthly index from
    a trade log of (entry_date, exit_date, direction).
    """
    pos = pd.Series(0.0, index=idx)
    dir_to_weight = {"Long": 1.0, "Short": -1.0, "Cash": 0.0}
    for _, row in log.iterrows():
        entry, exit_, d = row["entry_date"], row["exit_date"], row["direction"]
        weight = dir_to_weight.get(d, 0.0)
        # Position is held from entry (inclusive) to exit (exclusive).
        mask = (idx >= entry) & (idx < exit_)
        pos.loc[mask] = weight
    return pos


def _save(fig: go.Figure, name: str, *, narrative_alignment: str) -> None:
    fig_path = CHART_DIR / f"{name}.json"
    meta_path = CHART_DIR / f"{name}_meta.json"
    fig.write_json(fig_path)
    meta = {
        "chart_name": name,
        "pair_id": PAIR_ID,
        "palette_id": "mqr_default_2026",
        "rules_applied": ["VIZ-O1", "VIZ-BF1"],
        "narrative_alignment_note": narrative_alignment,
        "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": "scripts/generate_charts_permit_performance.py",
        "data_sources": [
            "results/permit_spy/winner_trade_log.csv",
            f"data/{PAIR_ID}_monthly_*.parquet",
        ],
    }
    with open(meta_path, "w") as fh:
        json.dump(meta, fh, indent=2)
    print(f"  WROTE -> {fig_path.name} (+ {meta_path.name})")


def chart_equity_curves(log: pd.DataFrame, master: pd.DataFrame) -> None:
    spy_ret = master["spy"].pct_change()
    pos = _build_strategy_position(log, master.index)

    # Strategy returns: position(t-1) × spy_ret(t), only where SPY exists.
    strat_ret = (pos.shift(1) * spy_ret).where(spy_ret.notna())
    cum_start = strat_ret.first_valid_index()
    if cum_start is None:
        raise RuntimeError("No valid strategy returns to plot.")

    strat_eq = (1 + strat_ret.loc[cum_start:].fillna(0)).cumprod()
    bh_eq = (1 + spy_ret.loc[cum_start:].fillna(0)).cumprod()

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=bh_eq.index, y=bh_eq.values,
        name="Buy & Hold SPY",
        line=dict(color=C_BENCHMARK, width=2, dash="dash"),
        hovertemplate="%{x|%Y-%m}<br>B&H = $%{y:.2f}<extra></extra>",
    ))
    fig.add_trace(go.Scatter(
        x=strat_eq.index, y=strat_eq.values,
        name="permit_mom1m / L6 / P3 (winner)",
        line=dict(color=C_STRATEGY, width=2.5),
        hovertemplate="%{x|%Y-%m}<br>Strategy = $%{y:.2f}<extra></extra>",
    ))

    # OOS boundary
    fig.add_vline(
        x=OOS_START, line=dict(color=C_OOS_LINE, width=1.5, dash="dot"),
        annotation_text="OOS start (2018-01)",
        annotation_position="top right",
        annotation=dict(font=dict(size=9, color=C_OOS_LINE)),
    )

    fig.update_layout(
        title=dict(
            text="Equity Curves — Strategy vs Buy & Hold SPY ($1 invested 1993-02)",
            font=dict(size=12),
        ),
        xaxis=dict(title=dict(text="Date", font=dict(size=10)), tickfont=dict(size=9)),
        yaxis=dict(
            title=dict(text="Cumulative value ($)", font=dict(size=10)),
            tickfont=dict(size=9),
            type="log",
        ),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right",
                    x=1, font=dict(size=10)),
        template="plotly_white",
        height=420,
        margin=dict(l=60, r=20, t=70, b=50),
    )

    _save(fig, "equity_curves",
          narrative_alignment="Strategy curve from trade log; full-sample with OOS boundary marked. "
                              "Log-scale Y-axis to keep early years legible alongside late-period growth.")


def chart_drawdown(log: pd.DataFrame, master: pd.DataFrame) -> None:
    spy_ret = master["spy"].pct_change()
    pos = _build_strategy_position(log, master.index)

    strat_ret = (pos.shift(1) * spy_ret).where(spy_ret.notna())
    cum_start = strat_ret.first_valid_index()

    strat_eq = (1 + strat_ret.loc[cum_start:].fillna(0)).cumprod()
    bh_eq = (1 + spy_ret.loc[cum_start:].fillna(0)).cumprod()

    strat_dd = (strat_eq / strat_eq.cummax() - 1) * 100
    bh_dd = (bh_eq / bh_eq.cummax() - 1) * 100

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=bh_dd.index, y=bh_dd.values,
        name="Buy & Hold SPY",
        fill="tozeroy",
        fillcolor="rgba(192,193,194,0.35)",
        line=dict(color=C_BENCH_DD, width=1),
        hovertemplate="%{x|%Y-%m}<br>B&H DD = %{y:.2f}%<extra></extra>",
    ))
    fig.add_trace(go.Scatter(
        x=strat_dd.index, y=strat_dd.values,
        name="Strategy",
        fill="tozeroy",
        fillcolor="rgba(216,84,39,0.35)",
        line=dict(color=C_DRAWDOWN, width=1.5),
        hovertemplate="%{x|%Y-%m}<br>Strategy DD = %{y:.2f}%<extra></extra>",
    ))

    fig.add_vline(
        x=OOS_START, line=dict(color=C_OOS_LINE, width=1.5, dash="dot"),
        annotation_text="OOS start (2018-01)",
        annotation_position="bottom right",
        annotation=dict(font=dict(size=9, color=C_OOS_LINE)),
    )

    strat_max = strat_dd.min()
    bh_max = bh_dd.min()
    strat_max_dt = strat_dd.idxmin()
    bh_max_dt = bh_dd.idxmin()

    fig.update_layout(
        title=dict(
            text=(f"Drawdown Comparison — Strategy max {strat_max:.1f}% "
                  f"({strat_max_dt:%Y-%m}) vs B&H {bh_max:.1f}% "
                  f"({bh_max_dt:%Y-%m})"),
            font=dict(size=12),
        ),
        xaxis=dict(title=dict(text="Date", font=dict(size=10)), tickfont=dict(size=9)),
        yaxis=dict(
            title=dict(text="Drawdown (%)", font=dict(size=10)),
            tickfont=dict(size=9),
        ),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right",
                    x=1, font=dict(size=10)),
        template="plotly_white",
        height=380,
        margin=dict(l=60, r=20, t=70, b=50),
    )

    _save(fig, "drawdown",
          narrative_alignment=f"Strategy max DD {strat_max:.1f}% vs B&H {bh_max:.1f}%. "
                              "Full-sample underwater plot with OOS boundary marked.")


def chart_walk_forward(log: pd.DataFrame, master: pd.DataFrame) -> None:
    spy_ret = master["spy"].pct_change()
    pos = _build_strategy_position(log, master.index)
    strat_ret = (pos.shift(1) * spy_ret).where(spy_ret.notna())
    cum_start = strat_ret.first_valid_index()

    strat = strat_ret.loc[cum_start:]
    bh = spy_ret.loc[cum_start:]

    # 24-month rolling Sharpe (annualised, monthly data)
    window = 24

    def roll_sharpe(s: pd.Series) -> pd.Series:
        m = s.rolling(window, min_periods=window).mean()
        sd = s.rolling(window, min_periods=window).std().replace(0, np.nan)
        return (m / sd) * np.sqrt(12)

    strat_rs = roll_sharpe(strat)
    bh_rs = roll_sharpe(bh)

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=bh_rs.index, y=bh_rs.values,
        name="Buy & Hold SPY",
        line=dict(color=C_BENCHMARK, width=2, dash="dash"),
        hovertemplate="%{x|%Y-%m}<br>B&H rolling Sharpe = %{y:.2f}<extra></extra>",
    ))
    fig.add_trace(go.Scatter(
        x=strat_rs.index, y=strat_rs.values,
        name="Strategy",
        line=dict(color=C_STRATEGY, width=2.5),
        hovertemplate="%{x|%Y-%m}<br>Strategy rolling Sharpe = %{y:.2f}<extra></extra>",
    ))

    # Zero reference line
    fig.add_hline(y=0, line=dict(color="#9E9FA1", width=1), opacity=0.5)
    fig.add_vline(
        x=OOS_START, line=dict(color=C_OOS_LINE, width=1.5, dash="dot"),
        annotation_text="OOS start (2018-01)",
        annotation_position="top right",
        annotation=dict(font=dict(size=9, color=C_OOS_LINE)),
    )

    fig.update_layout(
        title=dict(
            text=f"Walk-Forward Rolling {window}-Month Sharpe — Strategy vs Buy & Hold",
            font=dict(size=12),
        ),
        xaxis=dict(title=dict(text="Date", font=dict(size=10)), tickfont=dict(size=9)),
        yaxis=dict(title=dict(text="Annualised Sharpe", font=dict(size=10)),
                   tickfont=dict(size=9)),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right",
                    x=1, font=dict(size=10)),
        template="plotly_white",
        height=380,
        margin=dict(l=60, r=20, t=70, b=50),
    )

    _save(fig, "walk_forward",
          narrative_alignment=f"24-month rolling Sharpe for strategy and B&H, full sample. "
                              "Periods where strategy line is above B&H confirm the edge isn't "
                              "an artifact of one favourable window.")


def main() -> None:
    print(f"=== {PAIR_ID} performance charts ===\n")
    log = _load_trade_log()
    master = _load_master_monthly()
    print(f"  trade log: {len(log)} rows, {log['entry_date'].min().date()} -> {log['exit_date'].max().date()}")
    print(f"  master parquet: {len(master)} months, {master.index.min().date()} -> {master.index.max().date()}")
    print()
    chart_equity_curves(log, master)
    chart_drawdown(log, master)
    chart_walk_forward(log, master)


if __name__ == "__main__":
    main()
