#!/usr/bin/env python3
"""Chart (re)generation: Employment Cost Index (Total Compensation, ECIALLCIV) x SPY — #255 floored re-run.

Vera-hat producer for the eci_total_comp_spy pair — the fleet's FIRST QUARTERLY
pair. This script REGENERATES only the charts whose content changed under the
#255 floored-grid re-run (DATE_TAG 20261008), i.e. everything that depended on
the WINNER or on strategy/tournament/cross-period artifacts. The winner CHANGED:

    OLD (20260706): yoy_zscore_20q / T1_fixed_p75 / P3_long_short / PROCYCLICAL /
                    L6 quarters — OOS Sharpe 1.595 (look-ahead-tainted grid)
    NEW (20261008): hmm_stress (hmm_2state_prob_stress) / T3_zscore_1.0 (rolling,
                    LB12) / P1_long_cash / COUNTERCYCLICAL / L4 quarters —
                    OOS Sharpe 1.4089, ann ret 16.7%, max DD -4.4%, win 56%.

Honest framing (binding, per CLAUDE.md — do NOT oversell):
  * OOS Sharpe DROPPED vs the old winner (1.595 -> 1.409): the floored grid's best
    *executable* rule is weaker than the previous look-ahead-tainted one. Say so.
  * Direction flipped procyclical -> COUNTERCYCLICAL; the new direction is now
    CONSISTENT with the pair's countercyclical prior (direction_consistent=true),
    an improvement on the old contradictory winner — but the indicator remains
    empirically LAGGING (SPY->ECI Granger sig at every lag, ECI->SPY at none), so
    there is still no forward-causal mechanism behind the rule.
  * The traded signal is a DERIVED 2-state HMM wage-stress probability — more
    opaque/complex than a raw transform. True rule (resolved against the
    broker-style trade log): LONG SPY when the 4-quarter-lagged HMM wage-stress
    probability is BELOW its rolling z=1 threshold (low-stress regime = risk-on);
    CASH when above. In OOS it sat in CASH through the 2022 bear (and the COVID-Q1
    crash) — the edge is essentially drawdown avoidance on ~1 episode, 3 trades.
  * Found-in-search CANDIDATE: 25-QUARTER OOS (stronger small-sample caveat than
    any monthly pair), bootstrap p=0.184 (NOT significant at 5%, and WORSE than
    the old winner's 0.12), median valid combo 0.68 < B&H 0.80, no frozen-rule
    holdout. IS Sharpe is now +0.50 (was -0.23) — a mild improvement, still a
    search draw on a short window.

Charts REGENERATED by this script (output/charts/eci_total_comp_spy/plotly/):
    equity_curves, drawdown, walk_forward, lead_sharpe_distribution,
    tournament_scatter, tournament_sharpe_dist, subperiod_sharpe,
    rolling_correlation, structural_break, transfer_entropy, hmm_regime_probs.

Charts deliberately LEFT UNTOUCHED (winner-independent; input series / core-model
data unchanged between runs; carry hand-applied #186/#242 layout fixes):
    hero, regime_stats, correlation_heatmap, correlations_lead_view,
    granger_f_by_lag, ccf_prewhitened, local_projections, quantile_coef,
    history_zoom_{gfc,covid,inflation_2022}, chart_skip_* .

Author: Viz (Mode 2, #255 floored re-run). Date: 2026-10-09.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "scripts"))

from _nber import add_nber_shading  # noqa: E402
from _quartile_chart import QUARTILE_COLORS  # noqa: E402

PAIR = "eci_total_comp_spy"
DATE_TAG = "20261008"
RES = REPO / "results" / PAIR
CORE = RES / f"core_models_{DATE_TAG}"
OUT = REPO / "output" / "charts" / PAIR / "plotly"
OUT.mkdir(parents=True, exist_ok=True)

IND_LONG = "Employment Cost Index (Total Compensation)"
IND_SHORT = "ECI wage growth"
IND_YOY = "ECI YoY wage growth"
TGT = "SPY"

PALETTE_ID = "okabe_ito_2026"
PAL = json.loads((REPO / "docs/schemas/color_palette_registry.json").read_text())[
    "palettes"][PALETTE_ID]
C_IND = PAL["primary_data_trace"]
C_TGT = PAL["secondary_data_trace"]
C_POS = PAL["tertiary_data_trace"]
C_BENCH = PAL["benchmark_trace"]
C_NEUTRAL = PAL["hold_indicator"]
C_EVENT = PAL["event_marker_line"]
C_EXT = PAL["categorical_extended"]

ALLOWED_COLORS = ({str(v).lower() for v in PAL.values() if isinstance(v, str)}
                  | {c.lower() for c in C_EXT}
                  | {c.lower() for c in PAL["quartile_gradient"]}
                  | {c.lower() for c in QUARTILE_COLORS}
                  | {"rgba(108,122,137,0.15)", "rgba(0,114,178,0.25)",
                     "rgba(213,94,0,0.25)", "rgba(150,120,120,0.35)",
                     "rgba(213,94,0,0.35)", "rgba(153,153,153,0.45)", "#aec7e8"})

GENERATED_BY = "Viz — scripts/generate_charts_eci_total_comp_spy.py (#255 floored re-run)"
SRC_DATA = "data/eci_total_comp_spy_quarterly_latest.parquet"
YOY_COL = "eci_total_comp_pct_yoy"

# Winner combo coordinates (winner_summary.json raw_winner_row / bootstrap.csv).
WIN_SIGNAL_RAW = "hmm_stress"
WIN_THRESHOLD = "T3_zscore_1.0"
WIN_STRATEGY_RAW = "P1_long_cash_counter"
WIN_LOOKBACK = "LB12"
WIN_LEAD = 4
BOOT_P = 0.184  # winner_summary.notes / bootstrap.csv: winner bootstrap p=0.184 (vs resampled B&H)


# ── Loaders ─────────────────────────────────────────────────────────────────
def load_data() -> pd.DataFrame:
    return pd.read_parquet(REPO / "data" / f"{PAIR}_quarterly_latest.parquet")


def load_tournament() -> pd.DataFrame:
    return pd.read_csv(RES / f"tournament_results_{DATE_TAG}.csv")


def load_winner() -> dict:
    return json.loads((RES / "winner_summary.json").read_text())


# ── Gates ─────────────────────────────────────────────────────────────────
def _all_text(fig: go.Figure):
    if fig.layout.title and fig.layout.title.text:
        yield fig.layout.title.text
    for a in fig.layout.annotations or ():
        if a.text:
            yield a.text
    for tr in fig.data:
        if getattr(tr, "name", None):
            yield tr.name


def validate_intra_chart_consistency(fig: go.Figure, name: str) -> None:
    violations = []
    for i, tr in enumerate(fig.data):
        if not getattr(tr, "name", None) and getattr(tr, "showlegend", None) is not False:
            if tr.type not in ("heatmap",):
                violations.append(f"trace[{i}] ({tr.type}) unnamed with legend on")
    for tr in fig.data:
        cols = [getattr(getattr(tr, "line", None), "color", None),
                getattr(getattr(tr, "marker", None), "color", None),
                getattr(tr, "fillcolor", None)]
        mc = getattr(getattr(tr, "marker", None), "color", None)
        if isinstance(mc, (list, tuple)):
            cols.extend(mc)
        for col in cols:
            if isinstance(col, str) and col.lower() not in ALLOWED_COLORS \
                    and not col.lower().startswith("rgba(255,255,255"):
                violations.append(f"trace {getattr(tr,'name',None)!r}: color {col} not in {PALETTE_ID}")
    for txt in _all_text(fig):
        if str(txt).count("$") > 1:
            violations.append(f"VIZ-TX1: text has >1 literal '$': {txt!r}")
    if violations:
        for v in violations:
            print(f"    VIZ-IC1 VIOLATION [{name}]: {v}")
        raise SystemExit(f"VIZ-IC1 pre-save check failed for {name}; save blocked.")
    print(f"    VIZ-IC1 PASS [{name}]")


def assert_nber(fig: go.Figure, name: str) -> None:
    n = sum(1 for s in (fig.layout.shapes or ())
            if s.fillcolor and "rgba(150" in s.fillcolor.replace(" ", ""))
    if n == 0:
        raise SystemExit(f"VIZ-NBER1 FAIL: {name} has no NBER shading shapes.")
    print(f"    VIZ-NBER1 PASS [{name}]: {n} shape(s)")


def save_chart(name: str, fig: go.Figure, *, caption: str, alignment: str,
               rules: list, sources: list,
               reconciliation: dict | None = None,
               extra_meta: dict | None = None,
               nber_required: bool = True) -> None:
    if fig.layout.title is None or not fig.layout.title.text:
        raise SystemExit(f"{name} has no self-title (VIZ-O1).")
    validate_intra_chart_consistency(fig, name)
    if nber_required:
        assert_nber(fig, name)
    fig.write_json(OUT / f"{name}.json")
    meta = {
        "chart_name": name, "pair_id": PAIR, "palette_id": PALETTE_ID,
        "rules_applied": rules, "caption": caption,
        "narrative_alignment_note": alignment, "disposition": "consumed",
        "source_artifacts": sources, "reconciliation": reconciliation,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": GENERATED_BY,
    }
    if extra_meta:
        meta.update(extra_meta)
    (OUT / f"{name}_meta.json").write_text(json.dumps(meta, indent=2) + "\n")
    try:
        fig.write_image(str(OUT / f"_perceptual_check_{name}.png"),
                        width=1100, height=600, scale=1)
        png = " +perceptual png"
    except Exception as exc:  # Kaleido/Chrome may be unavailable; JSON is what matters.
        png = f" (png skipped: {type(exc).__name__})"
    print(f"  wrote {name}.json (+sidecar{png})")


def nber_swatch(fig: go.Figure) -> None:
    fig.add_trace(go.Scatter(
        x=[None], y=[None], mode="markers",
        marker=dict(size=12, color="rgba(150,120,120,0.35)", symbol="square"),
        name="NBER recession (shaded)", hoverinfo="skip"))


# ── Transfer entropy ──────────────────────────────────────────────────────
def chart_transfer_entropy():
    te = pd.read_csv(CORE / "transfer_entropy.csv")
    lab = {"indicator_to_target": f"{IND_SHORT} → {TGT}",
           "target_to_indicator": f"{TGT} → {IND_SHORT}"}
    fwd_p = float(te.loc[te["direction"] == "indicator_to_target", "permutation_p_value"].iloc[0])
    rev_p = float(te.loc[te["direction"] == "target_to_indicator", "permutation_p_value"].iloc[0])
    fig = go.Figure()
    for _, r in te.iterrows():
        fig.add_trace(go.Bar(
            x=[lab[r["direction"]]], y=[r["te_value"]],
            name=f"{lab[r['direction']]} (perm. p = {r['permutation_p_value']:.2f})",
            marker_color=C_IND if r["direction"] == "indicator_to_target" else C_TGT,
            text=[f"TE = {r['te_value']:.4f}<br>p = {r['permutation_p_value']:.2f}"],
            textposition="outside"))
    fig.update_layout(
        title=("Transfer Entropy: No Information Flow in Either Direction Between "
               f"{IND_SHORT} and {TGT}<br><sup>Tercile binning, 500 permutations "
               f"(~97 quarterly obs, low power); forward p = {fwd_p:.2f}, reverse "
               f"p = {rev_p:.2f} — neither significant</sup>"),
        yaxis_title="Transfer entropy (nats)", xaxis_title="Direction",
        template="plotly_white", height=400, showlegend=False)
    save_chart("transfer_entropy", fig,
               caption=(f"Transfer entropy between {IND_YOY} and {TGT} returns (tercile "
                        f"bins, 500 permutations). Forward (wages → {TGT}) p = {fwd_p:.2f}; "
                        f"reverse ({TGT} → wages) p = {rev_p:.2f}. Neither clears 5% — no "
                        f"non-linear channel rescues a forward reading, consistent with the "
                        f"absent forward Granger result (the indicator is lagging). On ~97 "
                        f"quarterly observations transfer entropy has low power, so read it "
                        f"as a directional check only."),
               alignment="Two-bar TE comparison; neither direction significant on the new run.",
               rules=["VIZ-IC1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/core_models_{DATE_TAG}/transfer_entropy.csv"],
               nber_required=False)


# ── HMM regime probabilities — NOW the traded winner signal ────────────────
def chart_hmm():
    h = pd.read_parquet(CORE / "hmm_states.parquet")
    summ = pd.read_csv(CORE / "hmm_summary.csv")
    hi = summ.loc[summ["state_label"] == "high_wage_inflation"].iloc[0]
    hi_pct = float(hi["frequency_pct"])
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=h.index, y=h["prob_stress"], mode="lines",
        name="P(high-wage-inflation regime) — the traded winner signal",
        fill="tozeroy", fillcolor="rgba(213,94,0,0.25)",
        line=dict(color=C_IND, width=1.2)))
    add_nber_shading(fig, x_min=h.index.min(), x_max=h.index.max())
    nber_swatch(fig)
    fig.update_layout(
        title=(f"Hidden Markov Model: the High-Wage-Inflation Regime Probability "
               f"IS the Winner Signal<br><sup>2-state HMM on {IND_SHORT}; the "
               f"high-wage-inflation state covers {hi_pct:.0f}% of quarters and peaks in "
               f"the 2021–23 surge. The rule trades this probability (lagged 4 quarters), "
               f"countercyclically</sup>"),
        xaxis_title="Date", yaxis_title="Probability of high-wage-inflation regime",
        template="plotly_white", height=420,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("hmm_regime_probs", fig,
               caption=(f"Probability that {IND_SHORT} is in its high-wage-inflation regime "
                        f"(2-state HMM). In THIS floored re-run the HMM probability is the "
                        f"TRADED WINNER SIGNAL (it was supporting context before): the rule "
                        f"holds {TGT} when the 4-quarter-lagged probability is BELOW its "
                        f"rolling z = 1 threshold (low-stress = risk-on) and steps to CASH "
                        f"when above — countercyclical. The high-wage-inflation state covers "
                        f"{hi_pct:.0f}% of quarters and peaks in the 2021–23 wage surge; "
                        f"concurrent {TGT} returns are better in the LOW state. An HMM-derived "
                        f"probability is more opaque than a raw transform — a complexity "
                        f"caution. Shaded bands mark NBER recessions."),
               alignment=("hmm_stress IS the winner signal in the floored re-run; reframed "
                          "from 'context' to 'traded signal', with the countercyclical rule "
                          "and the opacity caution stated."),
               rules=["VIZ-IC1", "VIZ-NBER1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/core_models_{DATE_TAG}/hmm_states.parquet",
                        f"results/{PAIR}/core_models_{DATE_TAG}/hmm_summary.csv"])


# ── Lead-Sharpe distribution (VIZ-LEAD1, GH #13) ───────────────────────────
def chart_lead_sharpe_distribution():
    lt = pd.read_csv(RES / f"lead_tournament_{DATE_TAG}.csv").sort_values("lead_quarters")
    wc = pd.read_csv(RES / f"lead_winner_curve_{DATE_TAG}.csv").sort_values("lead_quarters")
    w = load_winner()
    bh = float(w["bh_sharpe"])
    leads = lt["lead_quarters"].tolist()
    grid_lo, grid_hi = int(min(leads)), int(max(leads))
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=lt["lead_quarters"], y=lt["best_oos_sharpe"],
        marker_color=C_TGT, opacity=0.55,
        name="Best OOS Sharpe of ANY valid combo per lead (selection envelope)"))
    fig.add_trace(go.Scatter(
        x=wc["lead_quarters"], y=wc["oos_sharpe"], mode="lines+markers",
        line=dict(color=C_IND, width=2.2), marker=dict(size=7, color=C_IND),
        name="Winner signal (HMM wage-stress prob) traced across leads"))
    fig.add_trace(go.Scatter(
        x=[WIN_LEAD], y=[float(w["oos_sharpe"])], mode="markers",
        marker=dict(size=16, color=C_POS, symbol="star", line=dict(width=1, color="#000000")),
        name=f"Published winner L{WIN_LEAD}q (Sharpe {w['oos_sharpe']:.2f})"))
    fig.add_hline(y=bh, line=dict(color=C_BENCH, dash="dash", width=1.8),
                  annotation_text=f"Buy & Hold {TGT} = {bh:.2f}",
                  annotation_position="bottom right")
    fig.update_layout(
        title=(f"Lead Sweep: OOS Sharpe by Quarterly Lead — Published Winner L{WIN_LEAD}q "
               f"({w['oos_sharpe']:.2f}) Is the Grid Maximum<br><sup>Floored quarterly grid "
               f"L{grid_lo}–L{grid_hi}; the winner's OWN curve is positive at every scanned "
               f"lead and peaks at L{WIN_LEAD}q (internally consistent) — but every point is "
               f"search-conditioned on a 25-quarter window</sup>"),
        xaxis_title="Signal lead (quarters)", yaxis_title="OOS Sharpe ratio",
        template="plotly_white", height=480, margin=dict(b=150),
        legend=dict(orientation="h", yanchor="top", y=-0.18, xanchor="left", x=0))
    fig.update_xaxes(dtick=1)
    save_chart("lead_sharpe_distribution", fig,
               caption=(f"OOS Sharpe across the floored quarterly lead grid L{grid_lo}–"
                        f"L{grid_hi}. Bars are the best valid combo at each lead; the "
                        f"vermillion line traces the winner's own signal (the HMM wage-stress "
                        f"probability). The published winner (star) sits at L{WIN_LEAD}q with "
                        f"OOS Sharpe {w['oos_sharpe']:.2f} and is the grid maximum. Unlike the "
                        f"old look-ahead-tainted winner (which was negative at short leads), "
                        f"this signal's curve is POSITIVE at every scanned lead and peaks at "
                        f"L{WIN_LEAD}q — internally consistent. But the grid is short (only "
                        f"L{grid_lo}–L{grid_hi}), every point is search-conditioned on a "
                        f"25-quarter window, and the causality tests say the indicator is "
                        f"lagging — treat the ridge as descriptive, not a forecasting edge."),
               alignment=(f"Published L{WIN_LEAD}q winner is the grid maximum and its own "
                          f"lead-curve peaks there; honest note that the grid is short and "
                          f"search-conditioned."),
               rules=["VIZ-LEAD1", "VIZ-IC1", "VIZ-TX1", "VIZ-O1"],
               sources=[f"results/{PAIR}/lead_tournament_{DATE_TAG}.csv",
                        f"results/{PAIR}/lead_winner_curve_{DATE_TAG}.csv",
                        f"results/{PAIR}/winner_summary.json"],
               reconciliation={"winner_lead": WIN_LEAD,
                               "winner_oos_sharpe": round(float(w["oos_sharpe"]), 4),
                               "bh_sharpe": round(bh, 4)},
               extra_meta={"method_name": "lead_sharpe_distribution",
                           "expected_chart_type": "bar", "gh_issue": "13"},
               nber_required=False)


# ── Equity curves + drawdown ───────────────────────────────────────────────
def _strategy_returns() -> pd.DataFrame:
    d = pd.read_csv(RES / f"strategy_returns_{DATE_TAG}.csv", parse_dates=["date"])
    d["strategy_equity"] = (1 + d["strategy_return"]).cumprod()
    d["bh_equity"] = (1 + d["bh_return"]).cumprod()
    d["strategy_drawdown"] = d["strategy_equity"] / d["strategy_equity"].cummax() - 1
    d["bh_drawdown"] = d["bh_equity"] / d["bh_equity"].cummax() - 1
    return d


def chart_equity_curves():
    d = _strategy_returns()
    w = load_winner()
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=d["date"], y=d["strategy_equity"], mode="lines",
        name=f"ECI countercyclical Long/Cash rule (Sharpe {w['oos_sharpe']:.2f})",
        line=dict(color=C_IND, width=2.2)))
    fig.add_trace(go.Scatter(
        x=d["date"], y=d["bh_equity"], mode="lines",
        name=f"Buy & Hold {TGT} (Sharpe {w['bh_sharpe']:.2f})",
        line=dict(color=C_BENCH, width=1.8, dash="dash")))
    fig.add_vline(x=w["oos_period_start"], line=dict(color=C_EVENT, dash="dot", width=1.3))
    fig.add_annotation(x=w["oos_period_start"], y=0.96, yref="paper", showarrow=False,
                       xanchor="left", text="OOS begins",
                       font=dict(size=11, color=C_EVENT),
                       bgcolor=PAL["event_marker_label_bg"])
    add_nber_shading(fig, x_min=d["date"].min(), x_max=d["date"].max())
    nber_swatch(fig)
    fig.update_layout(
        title=(f"Countercyclical Long/Cash Overlay — a Candidate, Not a Verdict: ECI Rule "
               f"vs Buy & Hold {TGT}<br><sup>OOS {w['oos_period_start']} to "
               f"{w['oos_period_end']} ({w['oos_n']} QUARTERS): {w['oos_ann_return']*100:.1f}% "
               f"vs {w['bh_ann_return']*100:.1f}% annualized; OOS Sharpe dropped vs the old "
               f"look-ahead winner (1.60→{w['oos_sharpe']:.2f}); bootstrap p = {BOOT_P:.3f} "
               f"(NOT significant)</sup>"),
        xaxis_title="Date", yaxis_title="Growth of 1.00",
        template="plotly_white", height=480,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("equity_curves", fig,
               caption=(f"Cumulative growth of 1.00 for the saved strategy returns and "
                        f"buy-and-hold {TGT}. The rule raises Sharpe ({w['oos_sharpe']:.2f} vs "
                        f"{w['bh_sharpe']:.2f}) almost entirely by sitting in CASH through the "
                        f"2022 bear (and the COVID-Q1 crash) — the edge is drawdown avoidance "
                        f"on essentially one episode (3 trades). Honest flags: OOS Sharpe fell "
                        f"vs the old (look-ahead-tainted) winner; the window is 25 QUARTERS; "
                        f"the median valid combo (0.68) UNDERPERFORMS B&H (0.80); bootstrap "
                        f"p = {BOOT_P:.3f} is not significant; and the indicator is empirically "
                        f"LAGGING. Shaded bands mark NBER recessions."),
               alignment="Strategy series from strategy_returns; metrics from winner_summary; Sharpe-drop + fragility in title.",
               rules=["VIZ-IC1", "VIZ-NBER1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/strategy_returns_{DATE_TAG}.csv",
                        f"results/{PAIR}/winner_summary.json"])


def chart_drawdown():
    d = _strategy_returns()
    w = load_winner()
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=d["date"], y=d["strategy_drawdown"] * 100, mode="lines",
        name=f"Strategy drawdown (OOS max {w['oos_max_drawdown']*100:.1f}%)",
        fill="tozeroy", fillcolor="rgba(213,94,0,0.35)",
        line=dict(color=C_IND, width=1.5)))
    fig.add_trace(go.Scatter(
        x=d["date"], y=d["bh_drawdown"] * 100, mode="lines",
        name=f"Buy & Hold drawdown (OOS max {w['bh_max_drawdown']*100:.1f}%)",
        line=dict(color=C_BENCH, width=1.5, dash="dash")))
    fig.add_vline(x=w["oos_period_start"], line=dict(color=C_EVENT, dash="dot", width=1.3))
    add_nber_shading(fig, x_min=d["date"].min(), x_max=d["date"].max())
    nber_swatch(fig)
    fig.update_layout(
        title=(f"Drawdown Control Is the Defensible Virtue: "
               f"{w['oos_max_drawdown']*100:.1f}% vs {w['bh_max_drawdown']*100:.1f}% OOS"),
        xaxis_title="Date", yaxis_title="Drawdown (%)",
        template="plotly_white", height=430,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("drawdown", fig,
               caption=(f"Drawdown path for the ECI countercyclical Long/Cash rule and "
                        f"buy-and-hold {TGT}. In OOS the strategy's max drawdown is "
                        f"{w['oos_max_drawdown']*100:.1f}% versus "
                        f"{w['bh_max_drawdown']*100:.1f}% for buy-and-hold — achieved by "
                        f"stepping to CASH (not shorting) when the lagged wage-stress "
                        f"probability was high. Read the Sharpe advantage as volatility / "
                        f"drawdown avoidance, not forecasting skill, since the indicator is "
                        f"lagging. Shaded bands mark NBER recessions."),
               alignment="Drawdown from the saved quarterly return series; frames Sharpe as vol avoidance.",
               rules=["VIZ-IC1", "VIZ-NBER1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/strategy_returns_{DATE_TAG}.csv",
                        f"results/{PAIR}/winner_summary.json"])


# ── Tournament scatter + distribution ──────────────────────────────────────
def _tournament_frames():
    t = load_tournament()
    valid = t[t["valid"] & (t["signal"] != "BENCHMARK")]
    bench = t[t["signal"] == "BENCHMARK"]
    return t, valid, bench


def chart_tournament_scatter():
    t, valid, bench = _tournament_frames()
    invalid = t[(~t["valid"]) & (t["signal"] != "BENCHMARK")]
    w = load_winner()
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=invalid["annual_turnover"], y=invalid["oos_sharpe"], mode="markers",
        marker=dict(size=3, color="rgba(153,153,153,0.45)"), name="Invalid combos"))
    fig.add_trace(go.Scatter(
        x=valid["annual_turnover"], y=valid["oos_sharpe"], mode="markers",
        marker=dict(size=5, color=(valid["max_drawdown"] * 100),
                    colorscale="RdYlGn", colorbar=dict(title="Max DD (%)"), opacity=0.6),
        text=[f"{r['signal']}/{r['threshold']}/{r['strategy']}/L{r['lead_quarters']}q"
              for _, r in valid.iterrows()],
        hovertemplate="%{text}<br>Sharpe: %{y:.2f}<br>Turnover: %{x:.1f}/yr<extra></extra>",
        name="Valid strategies"))
    fig.add_trace(go.Scatter(
        x=[float(bench.iloc[0]["annual_turnover"])], y=[float(bench.iloc[0]["oos_sharpe"])],
        mode="markers", marker=dict(size=14, color=C_BENCH, symbol="diamond"),
        name=f"Buy & Hold {TGT} (Sharpe {float(bench.iloc[0]['oos_sharpe']):.2f})"))
    top5 = valid.nlargest(5, "oos_sharpe")
    fig.add_trace(go.Scatter(
        x=top5["annual_turnover"], y=top5["oos_sharpe"], mode="markers",
        marker=dict(size=12, color=C_POS, symbol="star", line=dict(width=1, color="#000000")),
        name="Top 5 by OOS Sharpe"))
    fig.update_layout(
        title=(f"Tournament: {len(t)-1:,} Strategy Combos ({len(valid):,} Valid) — Winner "
               f"OOS Sharpe {float(w['oos_sharpe']):.2f} vs Buy & Hold "
               f"{float(bench.iloc[0]['oos_sharpe']):.2f}<br><sup>Countercyclical Long/Cash "
               f"HMM-stress rule at L{WIN_LEAD}q; selected by the ECON-T3 cascade on a "
               f"25-quarter window</sup>"),
        xaxis_title="Annual turnover (trades per year)", yaxis_title="OOS Sharpe ratio",
        template="plotly_white", height=540, margin=dict(b=150),
        legend=dict(orientation="h", yanchor="top", y=-0.22, xanchor="left", x=0))
    save_chart("tournament_scatter", fig,
               caption=(f"All {len(t)-1:,} tournament combinations (OOS Sharpe vs annual "
                        f"turnover; color = max drawdown). {len(valid):,} pass validity; the "
                        f"Buy & Hold {TGT} diamond sits at Sharpe "
                        f"{float(bench.iloc[0]['oos_sharpe']):.2f}. The winner (a "
                        f"countercyclical Long/Cash HMM-stress rule at L{WIN_LEAD}q) is the "
                        f"grid maximum, selected by the ECON-T3 cascade — but it is the right "
                        f"tail of a search on 25 quarters; see the distribution chart."),
               alignment="Standard tournament scatter; benchmark via signal=='BENCHMARK' (ECON-T4); lead in quarters.",
               rules=["VIZ-IC1", "ECON-T4", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/tournament_results_{DATE_TAG}.csv"],
               nber_required=False)


def chart_tournament_dist():
    t, valid, bench = _tournament_frames()
    w = load_winner()
    med = float(valid["oos_sharpe"].median())
    wsharpe = float(w["oos_sharpe"])
    bh = float(bench.iloc[0]["oos_sharpe"])
    fig = go.Figure(go.Histogram(
        x=valid["oos_sharpe"], nbinsx=60, marker_color=C_TGT, opacity=0.75,
        name=f"Valid strategies (n = {len(valid):,})"))
    fig.add_vline(x=med, line=dict(color=C_NEUTRAL, dash="dot", width=1.5))
    fig.add_vline(x=bh, line=dict(color=C_BENCH, dash="dash", width=2))
    fig.add_vline(x=wsharpe, line=dict(color=C_IND, dash="dash", width=2))
    fig.add_annotation(x=wsharpe, y=1.0, yref="paper", showarrow=False, xanchor="right",
                       text=f"Winner = {wsharpe:.2f} (median {med:.2f})",
                       font=dict(size=12, color=C_IND), bgcolor=PAL["event_marker_label_bg"])
    bh_rel = "ABOVE" if bh >= med else "below"
    fig.add_annotation(x=bh, y=0.85, yref="paper", showarrow=False, xanchor="left",
                       text=f"Buy & Hold {TGT} = {bh:.2f} — {bh_rel} the median strategy",
                       font=dict(size=12, color=C_BENCH), bgcolor=PAL["event_marker_label_bg"])
    fig.update_layout(
        title=(f"Winner Is the Right Tail of an {len(valid):,}-Combo Search; the Median Rule "
               f"Underperforms Buy & Hold<br><sup>Median valid Sharpe {med:.2f} &lt; "
               f"Buy & Hold {bh:.2f} — the typical quarterly rule subtracts value; winner "
               f"bootstrap p = {BOOT_P:.3f} (n.s.)</sup>"),
        xaxis_title="OOS Sharpe ratio", yaxis_title="Number of strategies",
        template="plotly_white", height=440,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("tournament_sharpe_dist", fig,
               caption=(f"Distribution of OOS Sharpe across the {len(valid):,} valid strategy "
                        f"combos. The winner (Sharpe {wsharpe:.2f}) is the right tail; the "
                        f"median valid combo ({med:.2f}) sits BELOW buy & hold ({bh:.2f}) — the "
                        f"typical quarterly rule subtracts value, so the winner is a "
                        f"found-in-search draw (bootstrap p = {BOOT_P:.3f}, not significant at "
                        f"5%; no fresh final-exam holdout). On 25 quarters, treat it as a "
                        f"candidate, not a validated edge."),
               alignment=("VIZ-SCD1 position disclosure + B&H line; median&lt;B&H stated "
                          "explicitly; fragility flags in caption."),
               rules=["VIZ-SCD1", "ECON-T4", "VIZ-IC1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/tournament_results_{DATE_TAG}.csv",
                        f"results/{PAIR}/winner_summary.json"],
               reconciliation={"valid_count": len(valid), "median_oos_sharpe": round(med, 4),
                               "winner_oos_sharpe": round(wsharpe, 4),
                               "bh_oos_sharpe": round(bh, 4)},
               nber_required=False)


# ── Rolling correlation ────────────────────────────────────────────────────
def chart_rolling_correlation():
    rc = pd.read_csv(RES / f"rolling_correlation_{PAIR}.csv", parse_dates=["date"])
    sb = json.loads((RES / f"structural_break_{PAIR}.json").read_text())
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=rc["date"], y=rc["rolling_corr"], mode="lines",
        name="20-quarter rolling correlation", line=dict(color=C_TGT, width=2)))
    fig.add_hline(y=0, line_dash="dash", line_color=C_EVENT, line_width=1,
                  annotation_text="No correlation")
    add_nber_shading(fig, x_min=rc["date"].min(), x_max=rc["date"].max())
    nber_swatch(fig)
    verdict = sb["rolling_corr_stability_verdict"]
    _verdict_title = ("Sign-Unstable" if "unstable" in verdict
                      else "Moderately Stable" if "moderate" in verdict else "Sign-Stable")
    fig.update_layout(
        title=(f"{_verdict_title}, Variable Correlation: 20-Quarter Rolling Correlation, "
               f"{IND_YOY} vs {TGT} Returns<br><sup>Sign agreement "
               f"{sb['rolling_corr_sign_stability']:.2f} — verdict: "
               f"{verdict.replace('_', '-')}</sup>"),
        xaxis_title="Date", yaxis_title="Rolling correlation (r)",
        template="plotly_white", height=420, yaxis=dict(range=[-1, 1]),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("rolling_correlation", fig,
               caption=(f"20-quarter rolling correlation between {IND_YOY} and {TGT} "
                        f"quarterly returns. The sign agrees with its full-sample value "
                        f"{sb['rolling_corr_sign_stability']:.0%} of the time "
                        f"(verdict: {verdict.replace('_',' ')}) — more stable than in the "
                        f"prior run, though still variable, so the concurrent relationship "
                        f"remains descriptive. Shaded bands mark NBER recessions."),
               alignment="Stability verdict quoted from structural_break JSON, not hard-coded.",
               rules=["VIZ-CP1.2", "VIZ-NBER1", "VIZ-IC1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/rolling_correlation_{PAIR}.csv",
                        f"results/{PAIR}/structural_break_{PAIR}.json"])


# ── Structural break ───────────────────────────────────────────────────────
def chart_structural_break():
    sb = json.loads((RES / f"structural_break_{PAIR}.json").read_text())
    df = load_data()
    sig = df.loc[sb["sample_start"]:sb["sample_end"], YOY_COL].dropna()
    flagged = bool(sb["flagged"])
    verdict_txt = "A Structural Break IS Flagged" if flagged else "No Structural Break Detected"
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=sig.index, y=sig.values, mode="lines",
        name=f"{IND_YOY} (%)", line=dict(color=C_IND, width=1.8)))
    fig.add_vline(x=pd.Timestamp(sb["break_date"]).timestamp() * 1000,
                  line=dict(color=C_EVENT, dash="dash", width=2))
    fig.add_annotation(x=sb["break_date"], y=0.95, yref="paper", showarrow=False,
                       xanchor="left",
                       text=(f"Candidate break {sb['break_date'][:7]}: sup-F "
                             f"{sb['f_stat']:.2f}, bootstrap p = {sb['p_value']:.2f} "
                             f"— {'significant' if flagged else 'NOT significant'}"),
                       font=dict(size=12, color=C_EVENT),
                       bgcolor=PAL["event_marker_label_bg"])
    add_nber_shading(fig, x_min=sig.index.min(), x_max=sig.index.max())
    nber_swatch(fig)
    fig.update_layout(
        title=(f"{verdict_txt}: Quandt-Andrews sup-F Test on {IND_YOY} "
               f"(break {sb['break_date'][:7]}, p = {sb['p_value']:.2f})"),
        xaxis_title="Date", yaxis_title=f"{IND_YOY} (%)",
        template="plotly_white", height=420,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("structural_break", fig,
               caption=(f"{IND_YOY} over the test sample ({sb['sample_start'][:7]}–"
                        f"{sb['sample_end'][:7]}, n = {sb['n_obs']} quarters) with the "
                        f"Quandt-Andrews candidate break date ({sb['break_date'][:7]}). "
                        f"sup-F {sb['f_stat']:.2f}, residual-bootstrap p = {sb['p_value']:.2f} "
                        f"— {'a break is flagged' if flagged else 'NO significant break is flagged'}. "
                        f"Unlike the prior run (which flagged a 2009 break), this floored "
                        f"re-run finds no significant structural break. Shaded bands mark NBER "
                        f"recessions."),
               alignment="Annotation-driven; flagged state and values read from JSON (now NOT flagged).",
               rules=["VIZ-CP1.3", "VIZ-NBER1", "VIZ-IC1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/structural_break_{PAIR}.json", SRC_DATA],
               extra_meta={"break_date": sb["break_date"],
                           "annotation_strategy_id": "manual_override"})


# ── Sub-period Sharpe ──────────────────────────────────────────────────────
_EP_LABEL = {"dot_com": "Dot-Com 2000–02", "gfc": "GFC 2008–09",
             "covid": "COVID 2020", "china_2015": "China 2015–16"}


def chart_subperiod_sharpe():
    rows = pd.read_csv(RES / "subperiod_sharpe.csv")
    labels, values, colors, texts = [], [], [], []
    for _, r in rows.iterrows():
        lab = _EP_LABEL.get(r["episode"], r["episode"])
        if r["data_status"] == "insufficient_data" or pd.isna(r["ann_sharpe"]):
            labels.append(f"{lab}<br>(outside 2020+ OOS window)")
            values.append(0.0); colors.append(C_NEUTRAL); texts.append("no data")
        elif abs(float(r["ann_sharpe"])) < 1e-9:
            labels.append(f"{lab}<br>(strategy in cash)")
            values.append(0.0); colors.append(C_NEUTRAL); texts.append("cash")
        else:
            labels.append(lab)
            values.append(float(r["ann_sharpe"]))
            colors.append(C_POS if r["ann_sharpe"] >= 0 else C_IND)
            texts.append(f"{float(r['ann_sharpe']):+.2f}")
    n_eval = int(((rows["data_status"] == "validated") & rows["ann_sharpe"].notna()).sum())
    fig = go.Figure(go.Bar(x=labels, y=values, marker_color=colors,
                           text=texts, textposition="outside",
                           name="Annualized Sharpe by episode"))
    fig.add_hline(y=0, line=dict(color=C_NEUTRAL, width=0.6, dash="dot"))
    fig.update_layout(
        title=(f"Episode Durability Is Limited to One Episode: Winner Strategy by "
               f"Historical Episode<br><sup>Only {n_eval} of 4 canonical episodes (COVID) "
               f"falls inside the 2020+ OOS window; dot-com, GFC and China 2015 predate the "
               f"OOS split and are in-sample (insufficient data for the STRATEGY)</sup>"),
        xaxis_title="Historical episode", yaxis_title="Annualized Sharpe ratio",
        template="plotly_white", height=430, margin=dict(b=110), showlegend=False)
    save_chart("subperiod_sharpe", fig,
               caption=(f"Winner-strategy annualized Sharpe within each canonical stress "
                        f"episode. Only {n_eval} of 4 (COVID, Sharpe "
                        f"{float(rows.loc[rows['episode']=='covid','ann_sharpe'].iloc[0]):+.2f}) "
                        f"falls inside the 2020+ OOS window; dot-com, GFC and China 2015 "
                        f"predate the OOS split and are in-sample for the STRATEGY "
                        f"(insufficient data — the episodes cannot be scored, not that the "
                        f"data is missing). With only one evaluable episode, durability is "
                        f"'conditionally_durable' — the single biggest caveat on the edge."),
               alignment=("Three-state encoding; only COVID is inside the 2020+ OOS window; "
                          "one-episode durability stated as the headline caveat."),
               rules=["ECON-CP1", "VIZ-CP1.1", "VIZ-IC1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/subperiod_sharpe.csv"],
               nber_required=False)


# ── Walk-forward rolling Sharpe ────────────────────────────────────────────
def chart_walk_forward():
    d = pd.read_csv(RES / f"strategy_returns_{DATE_TAG}.csv", parse_dates=["date"]).set_index("date")
    w = load_winner()
    oos = d[(d.index >= w["oos_period_start"]) & (d.index <= w["oos_period_end"])]
    window, min_p, ann = 8, 6, 4  # QUARTERLY: 8-quarter (2yr) window, sqrt(4) annualization
    r_s = oos["strategy_return"].astype(float)
    r_b = oos["bh_return"].astype(float)
    roll_s = (r_s.rolling(window, min_periods=min_p).mean() * ann) / \
             (r_s.rolling(window, min_periods=min_p).std() * np.sqrt(ann) + 1e-12)
    roll_b = (r_b.rolling(window, min_periods=min_p).mean() * ann) / \
             (r_b.rolling(window, min_periods=min_p).std() * np.sqrt(ann) + 1e-12)
    reported = float(w["oos_sharpe"])
    y0, y1 = w["oos_period_start"][:4], w["oos_period_end"][:4]
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=roll_b.index, y=roll_b.values,
                             name=f"Buy & Hold {TGT}",
                             line=dict(color=C_BENCH, width=1.5, dash="dash")))
    fig.add_trace(go.Scatter(x=roll_s.index, y=roll_s.values,
                             name=f"Strategy rolling {window}-quarter Sharpe",
                             line=dict(color=C_IND, width=2)))
    add_nber_shading(fig, x_min=oos.index.min(), x_max=oos.index.max())
    nber_swatch(fig)
    fig.add_hline(y=reported, line=dict(color=C_POS, dash="dash", width=1.2),
                  annotation_text=f"Reported OOS Sharpe = {reported:.2f}",
                  annotation_position="top left")
    fig.add_hline(y=0, line=dict(color=C_NEUTRAL, width=0.6, dash="dot"))
    fig.update_layout(
        title=(f"Walk-Forward: Rolling 8-Quarter Sharpe vs Reported OOS Sharpe "
               f"{reported:.2f} (OOS {y0}–{y1})"),
        xaxis_title="Date", yaxis_title="Annualized Sharpe Ratio",
        template="plotly_white", height=400,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1))
    save_chart("walk_forward", fig,
               caption=(f"Rolling 8-quarter (2-year) annualized Sharpe of the winner strategy "
                        f"vs buy-and-hold {TGT} over the {w['oos_n']}-quarter out-of-sample "
                        f"window; the dashed reference line marks the reported OOS Sharpe "
                        f"({reported:.2f}). With only ~{w['oos_n']-window+1} rolling points on "
                        f"25 quarters the path is noisy by construction — read it as a "
                        f"stability sniff-test, not confirmation; the headline is an average "
                        f"over a variable ride, dominated by the cash period through 2022."),
               alignment="Rolling-Sharpe walk-forward; quarterly window; reference line reconciles with winner_summary OOS Sharpe.",
               rules=["ECON-SR1", "VIZ-IC1", "VIZ-NBER1", "VIZ-NS1", "VIZ-O1"],
               sources=[f"results/{PAIR}/strategy_returns_{DATE_TAG}.csv",
                        f"results/{PAIR}/winner_summary.json"])


def main():
    print(f"Regenerating #255 winner-dependent charts for {PAIR} (DATE_TAG {DATE_TAG})")
    chart_transfer_entropy()
    chart_hmm()
    chart_lead_sharpe_distribution()
    chart_equity_curves()
    chart_drawdown()
    chart_tournament_scatter()
    chart_tournament_dist()
    chart_rolling_correlation()
    chart_structural_break()
    chart_subperiod_sharpe()
    chart_walk_forward()
    print("Done. (hero/regime_stats/correlation_heatmap/correlations_lead_view/"
          "granger/ccf/local_projections/quantile/history_zoom left untouched — "
          "winner-independent, data unchanged.)")


if __name__ == "__main__":
    main()
