#!/usr/bin/env python3
"""
Data Pipeline: HY-IG Credit Spread → S&P 500 (SPY)
====================================================
Pair ID: hy_ig_spy  (fresh pair; v1 archived to hy_ig_spy_v1 in Wave 10G.1)

Wave 10G.4A — Data Stage Only
==============================
This script covers Stage 1 (data sourcing) and Stage 2 (derived signals)
only. Stages 3–7 (stationarity, regression, HMM, tournament, reporting) are
implemented by Econ Evan's dispatch in Wave 10G.4C, which extends this
pipeline in-place.

Indicator : HY-IG Credit Spread OAS (FRED BAMLH0A0HYM2 − BAMLC0A0CM)
Target    : SPDR S&P 500 ETF (SPY) adjusted close via Yahoo Finance
Date range: 2000-01-01 through current (2026-04-22 as of Wave 10G.4A)

Output
------
data/hy_ig_spy_daily_{start}_{end}.parquet   — master daily parquet
data/hy_ig_spy_daily_schema.json             — DATA-D5 column-level sidecar
(generated by: write_schema() at end of main)

DATA-D Compliance
-----------------
DATA-D5  : schema sidecar written alongside parquet
DATA-D6  : interpretation_metadata.json in results/hy_ig_spy/ (written separately)
DATA-D12 : column-suffix linter enforced before parquet save (pre-save gate)
DATA-D13 : display_name_registry update deferred to team bootstrap step

SOP version : data-agent-sop.md Wave 10G / team-standards.md Wave 10F
Author      : Data Dana (data-dana@idficient.com)
Date        : 2026-04-22
"""

import os
import sys
import json
import time
import warnings
import datetime

import numpy as np
import pandas as pd
from scipy import stats

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────────────────────

PAIR_ID     = "hy_ig_spy"
INDICATOR   = "HY-IG Credit Spread"
TARGET      = "S&P 500 (SPY)"
START_DATE  = "2000-01-01"
END_DATE    = datetime.date.today().strftime("%Y-%m-%d")   # 2026-04-22 as of Wave 10G.4A
DATE_START  = START_DATE.replace("-", "")                  # 20000101
DATE_END    = END_DATE.replace("-", "")                    # 20260422
DATE_TAG    = DATE_END

BASE_DIR    = "/workspaces/aig-rlic-plus"
DATA_DIR    = os.path.join(BASE_DIR, "data")
RESULTS_DIR = os.path.join(BASE_DIR, "results", PAIR_ID)

for d in [DATA_DIR, RESULTS_DIR]:
    os.makedirs(d, exist_ok=True)

PARQUET_PATH = os.path.join(DATA_DIR, f"{PAIR_ID}_daily_{DATE_START}_{DATE_END}.parquet")
SCHEMA_PATH  = os.path.join(DATA_DIR, f"{PAIR_ID}_daily_schema.json")

# ─────────────────────────────────────────────────────────────
# DATA-D12: COLUMN-SUFFIX LINTER (pre-save gate)
# ─────────────────────────────────────────────────────────────

# Columns that are unit-valued and require a canonical suffix.
# Linter checks that every numeric column in the DataFrame either:
#   (a) is a date/index column, or
#   (b) carries one of the approved suffixes.
CANONICAL_SUFFIXES = (
    "_bps", "_pct", "_ratio", "_usd",
    "_pct_mom", "_pct_yoy", "_ret", "_vol_ann_pct", "_idx",
    "_oas",    # spread levels quoted in percent (OAS: _oas suffix permitted per catalog)
    "_zscore_252d", "_zscore_504d",   # z-score composites (carry _ratio semantics)
    "_pctrank_504d", "_pctrank_1260d",
    "_roc_21d", "_roc_63d", "_roc_126d",    # rate-of-change in percent
    "_mom_21d", "_mom_63d", "_mom_252d",    # momentum in pp
    "_acceleration",                         # derived spread acceleration
    "_realized_vol_21d",                     # realized vol (decimal ratio)
    "_term_structure",                       # derived index difference
    "_momentum_13w",                         # NFCI index momentum
    "_fwd_1d", "_fwd_5d", "_fwd_21d",        # forward returns (decimal)
    "_fwd_63d", "_fwd_126d", "_fwd_252d",
)

# Non-signal numeric columns exempt from suffix rule (prices, raw index levels,
# raw FRED series that are consumed exclusively through derived columns).
# Raw FRED rates/indices are kept under their canonical short names (dgs10, dtb3, etc.)
# because renaming them would break downstream Evan stage expectations. Their units
# are declared in the DATA-D5 sidecar instead.
SUFFIX_EXEMPT = {
    "spy", "vix", "vix3m", "kbe", "iwm", "gold", "copper", "dxy", "hyg",
    "move_index",
    # Raw FRED rates (percent) — exempt; units declared in schema sidecar
    "dgs10", "dtb3", "dgs2", "nfci", "fed_funds_rate", "fsi", "initial_claims", "sofr",
    # Raw OAS levels (percent) — exempt; units declared in schema sidecar
    "hy_oas", "ig_oas", "bb_hy_oas", "ccc_hy_oas", "bbb_oas",
    # Derived index-unit columns — exempt (no unit-suffix convention for index levels)
    "vix_term_structure", "nfci_momentum_13w",
}

def lint_column_suffixes(df: pd.DataFrame) -> list:
    """
    DATA-D12 pre-save linter.
    Returns a list of violation strings. Empty list = PASS.
    """
    violations = []
    for col in df.columns:
        if col == "date":
            continue
        if col in SUFFIX_EXEMPT:
            continue
        if not any(col.endswith(s) for s in CANONICAL_SUFFIXES):
            violations.append(
                f"Column '{col}' stores unit-valued data but has no canonical unit "
                f"suffix (_bps/_pct/_ratio/etc.). DATA-D12 violation."
            )
    return violations


# ─────────────────────────────────────────────────────────────
# STAGE 1: DATA SOURCING
# ─────────────────────────────────────────────────────────────

def stage_data() -> dict:
    """
    Fetch raw series from FRED (13 series) and Yahoo Finance (10 tickers).

    Mirrors the series roster from hy_ig_v2_spy for continuity, using the
    canonical column names established in that pair's DATA-D5 sidecar.

    STOP-ON-FAILURE: if FRED or Yahoo returns no data for the core indicator
    or target, this function raises RuntimeError and the pipeline halts.
    """
    import yfinance as yf
    from fredapi import Fred

    print(f"\n{'='*60}")
    print(f"  STAGE 1 — DATA SOURCING")
    print(f"  Pair: {PAIR_ID}  |  {START_DATE} → {END_DATE}")
    print(f"{'='*60}")

    api_key = os.environ.get("FRED_API_KEY") or "952aa4d0c4b2057609fbf3ecc6954e58"
    fred = Fred(api_key=api_key)

    series: dict = {}

    # ── FRED series (13) ──────────────────────────────────────
    fred_map = [
        ("BAMLH0A0HYM2",  "hy_oas"),          # ICE BofA US HY OAS (%)
        ("BAMLC0A0CM",    "ig_oas"),           # ICE BofA US Corporate OAS (%)
        ("BAMLH0A1HYBB",  "bb_hy_oas"),        # ICE BofA BB HY OAS (%)
        ("BAMLH0A3HYC",   "ccc_hy_oas"),       # ICE BofA CCC & Lower OAS (%)
        ("DGS10",         "dgs10"),            # US 10Y Treasury CMR (%)
        ("DTB3",          "dtb3"),             # US 3M T-Bill Secondary Market (%)
        ("DGS2",          "dgs2"),             # US 2Y Treasury CMR (%)
        ("NFCI",          "nfci"),             # Chicago Fed NFCI (index, weekly)
        ("DFF",           "fed_funds_rate"),   # Effective Fed Funds Rate (%)
        ("BAMLC0A4CBBB",  "bbb_oas"),          # ICE BofA BBB Corporate OAS (%)
        ("STLFSI4",       "fsi"),              # St. Louis Fed FSI (index)
        ("ICSA",          "initial_claims"),   # Initial Jobless Claims (count, weekly)
        ("SOFR",          "sofr"),             # SOFR (%)
    ]

    for sid, name in fred_map:
        for attempt in range(3):
            try:
                s = fred.get_series(sid, observation_start=START_DATE, observation_end=END_DATE)
                series[name] = s.astype(float)
                v = s.dropna()
                print(f"  [FRED] {sid:20s} -> {name:20s}: {len(v):5d} obs  "
                      f"({v.index.min().date()} to {v.index.max().date()})")
                break
            except Exception as e:
                if attempt < 2:
                    time.sleep(1)
                else:
                    print(f"  [FRED] {sid} FAILED after 3 attempts: {e}")

    # ── OAS Series Splice (FRED truncation workaround) ────────
    # As of 2026-04-22, FRED BAMLH0A0HYM2 / BAMLC0A0CM / BAMLH0A1HYBB /
    # BAMLH0A3HYC / BAMLC0A4CBBB only return observations from 2023-04-24
    # onward (FRED series observation_start = 2023-04-24; series was truncated
    # at source). The v1 parquet (hy_ig_spy_v1_daily_20000101_20251231.parquet)
    # carries these OAS series from 2000-01-03 through 2025-12-31.
    # Strategy: back-fill pre-2023 from v1 parquet, then overlay the live
    # FRED values for the intersection and extension beyond 2025-12-31.
    # This is the same splice pattern used for SOFR in the v2 pipeline.
    oas_cols = {
        "hy_oas": "hy_oas",
        "ig_oas": "ig_oas",
        "bb_hy_oas": "bb_hy_oas",
        "ccc_hy_oas": "ccc_hy_oas",
        "bbb_oas": "bbb_oas",
    }
    v1_parquet_path = os.path.join(DATA_DIR, "hy_ig_spy_v1_daily_20000101_20251231.parquet")
    if os.path.exists(v1_parquet_path):
        v1 = pd.read_parquet(v1_parquet_path)
        for col, tgt in oas_cols.items():
            if col in v1.columns and tgt in series:
                # Combine: v1 history, then overlay with fresh FRED where available
                hist = v1[col].dropna()
                live = series[tgt].dropna()
                combined = hist.combine_first(live)   # live overrides hist on overlap
                series[tgt] = combined.astype(float)
                v = series[tgt].dropna()
                print(f"  [SPLICE] {col:20s}: v1+FRED spliced → "
                      f"{len(v):5d} obs ({v.index.min().date()} to {v.index.max().date()})")
            elif col in v1.columns and tgt not in series:
                # FRED fetch failed entirely — fall back to v1 only
                series[tgt] = v1[col].astype(float)
                v = series[tgt].dropna()
                print(f"  [SPLICE] {col:20s}: v1 only (FRED failed) → "
                      f"{len(v):5d} obs ({v.index.min().date()} to {v.index.max().date()})")
    else:
        print(f"  [WARN] v1 parquet not found at {v1_parquet_path}; OAS history limited to FRED coverage.")

    # Halt on missing core indicator
    if "hy_oas" not in series or "ig_oas" not in series:
        raise RuntimeError(
            "STOP: Could not source BAMLH0A0HYM2 or BAMLC0A0CM "
            "(core HY-IG OAS series) from FRED or v1 splice. "
            "Cannot build hy_ig_spread_pct. Check network / API key and rerun."
        )

    # ── Yahoo Finance (10 tickers) ────────────────────────────
    yf_map = [
        ("SPY",       "spy"),
        ("^VIX",      "vix"),
        ("^VIX3M",    "vix3m"),
        ("KBE",       "kbe"),
        ("IWM",       "iwm"),
        ("^MOVE",     "move_index"),
        ("GC=F",      "gold"),
        ("HG=F",      "copper"),
        ("DX-Y.NYB",  "dxy"),
        ("HYG",       "hyg"),
    ]

    for ticker, name in yf_map:
        try:
            dl = yf.download(ticker, start=START_DATE, end=END_DATE,
                             progress=False, auto_adjust=True)
            if isinstance(dl.columns, pd.MultiIndex):
                dl.columns = dl.columns.get_level_values(0)
            s = dl["Close"]
            s.index = s.index.tz_localize(None) if s.index.tz else s.index
            series[name] = s.astype(float)
            print(f"  [YF]   {ticker:12s} -> {name:15s}: {len(s):5d} obs  "
                  f"({s.index.min().date()} to {s.index.max().date()})")
        except Exception as e:
            print(f"  [YF]   {ticker} FAILED: {e}")

    # Halt on missing target
    if "spy" not in series:
        raise RuntimeError(
            "STOP: Yahoo Finance fetch failed for SPY (target asset). "
            "Cannot build hy_ig_spy pair. Check network and rerun."
        )

    print(f"\n  Total series sourced: {len(series)}")
    return series


# ─────────────────────────────────────────────────────────────
# STAGE 2: DERIVED SIGNALS
# ─────────────────────────────────────────────────────────────

def stage_derived(series: dict) -> pd.DataFrame:
    """
    Align raw series to business-day calendar and build all derived
    signals. Column naming follows DATA-D12 suffix conventions.

    Derived columns produced:
    - hy_ig_spread_pct        : HY OAS − IG OAS (pct)
    - hy_ig_zscore_252d/504d  : rolling z-scores (ratio)
    - hy_ig_pctrank_504d/1260d: rolling percentile ranks (ratio)
    - hy_ig_roc_21/63/126d    : rate-of-change (pct)
    - hy_ig_mom_21/63/252d    : level momentum (pct units)
    - hy_ig_acceleration      : 2nd-diff proxy (pct units)
    - ccc_bb_spread           : within-HY quality spread (pct)
    - hy_ig_realized_vol_21d  : annualized vol of spread changes (ratio)
    - vix_term_structure      : VIX3M − VIX (index units)
    - yield_spread_10y3m      : 10Y − 3M (pct)
    - yield_spread_10y2y      : 10Y − 2Y (pct)
    - bank_smallcap_ratio     : KBE / IWM (ratio)
    - nfci_momentum_13w       : 13-week NFCI change (index)
    - bbb_ig_spread           : BBB − IG OAS (pct)
    - spy_ret                 : SPY daily return (decimal)
    - spy_fwd_{1/5/21/63/126/252}d : forward returns (decimal)
    """
    print(f"\n{'='*60}")
    print(f"  STAGE 2 — DERIVED SIGNALS")
    print(f"{'='*60}")

    bdays = pd.bdate_range(START_DATE, END_DATE)
    df = pd.DataFrame(index=bdays)
    df.index.name = "date"

    weekly_cols = {"nfci", "fsi", "initial_claims"}

    all_raw_cols = [
        "hy_oas", "ig_oas", "bb_hy_oas", "ccc_hy_oas",
        "dgs10", "dtb3", "dgs2", "nfci", "fed_funds_rate",
        "bbb_oas", "fsi", "initial_claims", "sofr",
        "spy", "vix", "vix3m", "kbe", "iwm",
        "move_index", "gold", "copper", "dxy", "hyg",
    ]

    for col in all_raw_cols:
        if col not in series:
            print(f"  [WARN] raw column '{col}' not in fetched series — skipped.")
            continue
        s = series[col].copy()
        limit = 10 if col in weekly_cols else 5
        if col in weekly_cols:
            # Shift weekend release dates to preceding Friday for bday alignment
            def _to_bday(d):
                if d.weekday() < 5:
                    return d
                return d - pd.Timedelta(days=d.weekday() - 4)
            s.index = s.index.map(_to_bday)
            s = s[~s.index.duplicated(keep="last")]
        df[col] = s.reindex(bdays).ffill(limit=limit)

    # ── Core indicator: HY-IG spread in percent ───────────────
    df["hy_ig_spread_pct"] = df["hy_oas"] - df["ig_oas"]
    spread = df["hy_ig_spread_pct"]

    # ── Z-scores ──────────────────────────────────────────────
    df["hy_ig_zscore_252d"] = (
        (spread - spread.rolling(252, min_periods=200).mean())
        / spread.rolling(252, min_periods=200).std()
    )
    df["hy_ig_zscore_504d"] = (
        (spread - spread.rolling(504, min_periods=400).mean())
        / spread.rolling(504, min_periods=400).std()
    )

    # ── Percentile ranks ──────────────────────────────────────
    df["hy_ig_pctrank_504d"] = spread.rolling(504, min_periods=400).apply(
        lambda x: stats.rankdata(x)[-1] / len(x), raw=True
    )
    df["hy_ig_pctrank_1260d"] = spread.rolling(1260, min_periods=1000).apply(
        lambda x: stats.rankdata(x)[-1] / len(x), raw=True
    )

    # ── Rates-of-change (%) ───────────────────────────────────
    df["hy_ig_roc_21d"]  = (spread / spread.shift(21)  - 1) * 100
    df["hy_ig_roc_63d"]  = (spread / spread.shift(63)  - 1) * 100
    df["hy_ig_roc_126d"] = (spread / spread.shift(126) - 1) * 100

    # ── Momentum (absolute pp change) ────────────────────────
    df["hy_ig_mom_21d"]  = spread - spread.shift(21)
    df["hy_ig_mom_63d"]  = spread - spread.shift(63)
    df["hy_ig_mom_252d"] = spread - spread.shift(252)

    # ── Acceleration (2nd-diff proxy) ────────────────────────
    df["hy_ig_acceleration"] = df["hy_ig_roc_21d"] - df["hy_ig_roc_21d"].shift(21)

    # ── Quality spread: CCC − BB ──────────────────────────────
    # DATA-D12: column suffixed _pct (spread in percentage points)
    if "ccc_hy_oas" in df.columns and "bb_hy_oas" in df.columns:
        df["ccc_bb_spread_pct"] = df["ccc_hy_oas"] - df["bb_hy_oas"]
    else:
        print("  SKIP ccc_bb_spread_pct: missing ccc_hy_oas or bb_hy_oas")

    # ── Realized volatility of spread changes ─────────────────
    df["hy_ig_realized_vol_21d"] = spread.diff().rolling(21, min_periods=15).std()

    # ── Cross-market derived signals ──────────────────────────
    def _safe_sub(a, b, name):
        if a in df.columns and b in df.columns:
            df[name] = df[a] - df[b]
        else:
            print(f"  SKIP {name}: missing {a if a not in df.columns else b}")

    def _safe_div(a, b, name):
        if a in df.columns and b in df.columns:
            df[name] = df[a] / df[b]
        else:
            print(f"  SKIP {name}: missing {a if a not in df.columns else b}")

    # DATA-D12: derived spread/ratio columns carry _pct or _ratio suffixes
    _safe_sub("vix3m",  "vix",    "vix_term_structure")     # index units, exempt
    _safe_sub("dgs10",  "dtb3",   "yield_spread_10y3m_pct")
    _safe_sub("dgs10",  "dgs2",   "yield_spread_10y2y_pct")
    _safe_div("kbe",    "iwm",    "bank_smallcap_ratio")
    if "nfci" in df.columns:
        df["nfci_momentum_13w"] = df["nfci"] - df["nfci"].shift(65)
    _safe_sub("bbb_oas", "ig_oas", "bbb_ig_spread_pct")

    # ── Forward SPY returns (6 horizons) ─────────────────────
    spy = df["spy"]
    df["spy_ret"]     = spy.pct_change()
    df["spy_fwd_1d"]  = spy.pct_change(1).shift(-1)
    df["spy_fwd_5d"]  = spy.shift(-5)  / spy - 1
    df["spy_fwd_21d"] = spy.shift(-21) / spy - 1
    df["spy_fwd_63d"] = spy.shift(-63) / spy - 1
    df["spy_fwd_126d"]= spy.shift(-126)/ spy - 1
    df["spy_fwd_252d"]= spy.shift(-252)/ spy - 1

    # ── Drop rows missing core variables ─────────────────────
    df = df.dropna(subset=["hy_ig_spread_pct", "spy"])

    print(f"  Master DataFrame: {df.shape[0]} rows × {df.shape[1]} cols")
    print(f"  Date range: {df.index.min().date()} to {df.index.max().date()}")

    key_cols = ["hy_ig_spread_pct", "hy_ig_zscore_252d", "hy_ig_roc_21d", "spy", "vix"]
    for c in key_cols:
        if c in df.columns:
            pct_missing = df[c].isna().mean() * 100
            print(f"  Missing: {c:32s} {pct_missing:.1f}%")

    return df


# ─────────────────────────────────────────────────────────────
# SCHEMA SIDECAR (DATA-D5)
# ─────────────────────────────────────────────────────────────

SCHEMA_COLUMNS = {
    "date": {
        "dtype": "datetime64[ns]",
        "unit": "date",
        "display_name": "Date",
        "direction": "neutral",
        "description": (
            "Daily trading-date index (parquet index column). "
            "Aligned to NYSE business calendar; spans 2000-01-03 through 2026-04-22."
        )
    },
    "hy_oas": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY OAS (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA US High Yield Option-Adjusted Spread, quoted in percentage points "
            "(e.g. 4.68 = 4.68%)."
        ),
        "source_reference": "FRED:BAMLH0A0HYM2",
        "refresh_ttl_days": 1
    },
    "ig_oas": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "IG OAS (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA US Corporate (Investment Grade) Option-Adjusted Spread, "
            "quoted in percentage points."
        ),
        "source_reference": "FRED:BAMLC0A0CM",
        "refresh_ttl_days": 1
    },
    "bb_hy_oas": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "BB HY OAS (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA BB US High Yield OAS (sub-IG but highest-rated HY slice), "
            "in percent."
        ),
        "source_reference": "FRED:BAMLH0A1HYBB",
        "refresh_ttl_days": 1
    },
    "ccc_hy_oas": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "CCC HY OAS (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA CCC & Lower US High Yield OAS (lowest-rated HY tranche), "
            "in percent."
        ),
        "source_reference": "FRED:BAMLH0A3HYC",
        "refresh_ttl_days": 1
    },
    "dgs10": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "US 10Y Treasury Yield (%)",
        "direction": "neutral",
        "description": "10-Year Treasury Constant Maturity Rate, in percent.",
        "source_reference": "FRED:DGS10",
        "refresh_ttl_days": 1
    },
    "dtb3": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "US 3M T-Bill Yield (%)",
        "direction": "neutral",
        "description": "3-Month Treasury Bill Secondary Market Rate, in percent.",
        "source_reference": "FRED:DTB3",
        "refresh_ttl_days": 1
    },
    "dgs2": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "US 2Y Treasury Yield (%)",
        "direction": "neutral",
        "description": "2-Year Treasury Constant Maturity Rate, in percent.",
        "source_reference": "FRED:DGS2",
        "refresh_ttl_days": 1
    },
    "nfci": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "Chicago Fed NFCI",
        "direction": "lower_is_better",
        "description": (
            "Chicago Fed National Financial Conditions Index; positive = "
            "tighter-than-average conditions, negative = looser. Weekly release, "
            "LVCF-aligned to daily."
        ),
        "source_reference": "FRED:NFCI",
        "refresh_ttl_days": 7
    },
    "fed_funds_rate": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "Fed Funds Rate (%)",
        "direction": "neutral",
        "description": "Effective Federal Funds Rate, in percent.",
        "source_reference": "FRED:DFF",
        "refresh_ttl_days": 1
    },
    "bbb_oas": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "BBB OAS (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA BBB US Corporate OAS (lowest-rated IG tranche), in percent."
        ),
        "source_reference": "FRED:BAMLC0A4CBBB",
        "refresh_ttl_days": 1
    },
    "fsi": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "St. Louis Fed Financial Stress Index",
        "direction": "lower_is_better",
        "description": (
            "St. Louis Fed Financial Stress Index (STLFSI4); higher = more systemic "
            "stress. Standardized composite."
        ),
        "source_reference": "FRED:STLFSI4",
        "refresh_ttl_days": 1
    },
    "initial_claims": {
        "dtype": "float64",
        "unit": "count",
        "display_name": "Initial Jobless Claims",
        "direction": "lower_is_better",
        "description": (
            "Weekly initial unemployment-insurance claims filed, US total. "
            "LVCF-aligned to daily from weekly release."
        ),
        "source_reference": "FRED:ICSA",
        "refresh_ttl_days": 7
    },
    "sofr": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "SOFR (%)",
        "direction": "neutral",
        "description": (
            "Secured Overnight Financing Rate, in percent. "
            "Start 2018-04-03; earlier dates backfilled with Fed Funds proxy."
        ),
        "source_reference": "FRED:SOFR",
        "refresh_ttl_days": 1
    },
    "spy": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "SPY Close ($)",
        "direction": "higher_is_better",
        "description": (
            "SPDR S&P 500 ETF adjusted close price in USD. "
            "Target asset for the hy_ig_spy pair."
        ),
        "source_reference": "yahoo:SPY",
        "refresh_ttl_days": 1
    },
    "vix": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "VIX Index Level",
        "direction": "lower_is_better",
        "description": (
            "CBOE Volatility Index — 30-day implied volatility of S&P 500 options, "
            "quoted as an index level (also interpretable as annualized percent)."
        ),
        "source_reference": "yahoo:^VIX",
        "refresh_ttl_days": 1
    },
    "vix3m": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "VIX3M Index Level",
        "direction": "lower_is_better",
        "description": (
            "CBOE 3-Month Volatility Index — forward-looking implied vol at 3M horizon."
        ),
        "source_reference": "yahoo:^VIX3M",
        "refresh_ttl_days": 1
    },
    "kbe": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "KBE Close ($)",
        "direction": "higher_is_better",
        "description": (
            "SPDR S&P Bank ETF adjusted close, used for bank/small-cap regime indicator."
        ),
        "source_reference": "yahoo:KBE",
        "refresh_ttl_days": 1
    },
    "iwm": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "IWM Close ($)",
        "direction": "higher_is_better",
        "description": (
            "iShares Russell 2000 ETF adjusted close — small-cap equity proxy for "
            "regime overlay."
        ),
        "source_reference": "yahoo:IWM",
        "refresh_ttl_days": 1
    },
    "move_index": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "MOVE Index",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA MOVE Index — Treasury option-implied volatility index."
        ),
        "source_reference": "yahoo:^MOVE",
        "refresh_ttl_days": 1
    },
    "gold": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "Gold Spot ($/oz)",
        "direction": "neutral",
        "description": "Gold spot price in USD per troy ounce.",
        "source_reference": "yahoo:GC=F",
        "refresh_ttl_days": 1
    },
    "copper": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "Copper Spot ($/lb)",
        "direction": "higher_is_better",
        "description": (
            "Copper spot price in USD per pound. Higher = stronger global industrial "
            "demand."
        ),
        "source_reference": "yahoo:HG=F",
        "refresh_ttl_days": 1
    },
    "dxy": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "DXY Dollar Index",
        "direction": "neutral",
        "description": (
            "ICE US Dollar Index — USD vs basket of 6 major currencies."
        ),
        "source_reference": "yahoo:DX-Y.NYB",
        "refresh_ttl_days": 1
    },
    "hyg": {
        "dtype": "float64",
        "unit": "price",
        "display_name": "HYG Close ($)",
        "direction": "higher_is_better",
        "description": (
            "iShares iBoxx $ High Yield Corporate Bond ETF adjusted close."
        ),
        "source_reference": "yahoo:HYG",
        "refresh_ttl_days": 1
    },
    "hy_ig_spread_pct": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Credit Spread (%)",
        "direction": "lower_is_better",
        "description": (
            "ICE BofA US High Yield OAS minus ICE BofA US Corporate OAS, expressed in "
            "percentage points (e.g. 3.52 = 3.52%). Primary indicator for hy_ig_spy pair. "
            "Column carries _pct suffix per DATA-D12."
        ),
        "source_reference": "derived: BAMLH0A0HYM2 - BAMLC0A0CM",
        "refresh_ttl_days": 1
    },
    "hy_ig_zscore_252d": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "HY-IG Spread Z-Score (252d)",
        "direction": "lower_is_better",
        "description": (
            "Standardized hy_ig_spread_pct vs trailing 252-day rolling mean and standard "
            "deviation. Dimensionless."
        ),
        "source_reference": "derived: (hy_ig_spread_pct - rolling_mean_252) / rolling_std_252",
        "refresh_ttl_days": 1
    },
    "hy_ig_zscore_504d": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "HY-IG Spread Z-Score (504d)",
        "direction": "lower_is_better",
        "description": (
            "Standardized hy_ig_spread_pct vs trailing 504-day (~2y) rolling window. "
            "Dimensionless."
        ),
        "source_reference": "derived: (hy_ig_spread_pct - rolling_mean_504) / rolling_std_504",
        "refresh_ttl_days": 1
    },
    "hy_ig_pctrank_504d": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "HY-IG Spread %-Rank (504d)",
        "direction": "lower_is_better",
        "description": (
            "Percentile rank (0 to 1) of hy_ig_spread_pct within trailing 504-day window. "
            "1.0 = widest-in-window."
        ),
        "source_reference": "derived: percentile_rank(hy_ig_spread_pct, window=504)",
        "refresh_ttl_days": 1
    },
    "hy_ig_pctrank_1260d": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "HY-IG Spread %-Rank (1260d)",
        "direction": "lower_is_better",
        "description": (
            "Percentile rank (0 to 1) of hy_ig_spread_pct within trailing 1260-day (~5y) "
            "window."
        ),
        "source_reference": "derived: percentile_rank(hy_ig_spread_pct, window=1260)",
        "refresh_ttl_days": 1
    },
    "hy_ig_roc_21d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 21d Rate-of-Change (%)",
        "direction": "lower_is_better",
        "description": (
            "21-trading-day percent-change of hy_ig_spread_pct. "
            "Positive = spread widened (bearish)."
        ),
        "source_reference": "derived: (spread[t] / spread[t-21] - 1) * 100",
        "refresh_ttl_days": 1
    },
    "hy_ig_roc_63d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 63d Rate-of-Change (%)",
        "direction": "lower_is_better",
        "description": (
            "63-trading-day (~3M) percent-change of hy_ig_spread_pct."
        ),
        "source_reference": "derived: (spread[t] / spread[t-63] - 1) * 100",
        "refresh_ttl_days": 1
    },
    "hy_ig_roc_126d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 126d Rate-of-Change (%)",
        "direction": "lower_is_better",
        "description": (
            "126-trading-day (~6M) percent-change of hy_ig_spread_pct."
        ),
        "source_reference": "derived: (spread[t] / spread[t-126] - 1) * 100",
        "refresh_ttl_days": 1
    },
    "hy_ig_mom_21d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 21d Momentum (pp)",
        "direction": "lower_is_better",
        "description": (
            "21-trading-day difference (in percentage points) of hy_ig_spread_pct. "
            "Unit matches the parent spread (percent)."
        ),
        "source_reference": "derived: hy_ig_spread_pct[t] - hy_ig_spread_pct[t-21]",
        "refresh_ttl_days": 1
    },
    "hy_ig_mom_63d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 63d Momentum (pp)",
        "direction": "lower_is_better",
        "description": (
            "63-trading-day difference (in percentage points) of hy_ig_spread_pct."
        ),
        "source_reference": "derived: hy_ig_spread_pct[t] - hy_ig_spread_pct[t-63]",
        "refresh_ttl_days": 1
    },
    "hy_ig_mom_252d": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread 252d Momentum (pp)",
        "direction": "lower_is_better",
        "description": (
            "252-trading-day (~1y) difference in percentage points of hy_ig_spread_pct."
        ),
        "source_reference": "derived: hy_ig_spread_pct[t] - hy_ig_spread_pct[t-252]",
        "refresh_ttl_days": 1
    },
    "hy_ig_acceleration": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "HY-IG Spread Acceleration",
        "direction": "lower_is_better",
        "description": (
            "Change in rate-of-change (second-difference proxy) of hy_ig_spread_pct, "
            "expressed in percent. Captures inflection dynamics."
        ),
        "source_reference": "derived: hy_ig_roc_21d[t] - hy_ig_roc_21d[t-21]",
        "refresh_ttl_days": 1
    },
    "ccc_bb_spread_pct": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "CCC-BB HY Quality Spread (%)",
        "direction": "lower_is_better",
        "description": (
            "Within-HY quality spread — CCC OAS minus BB OAS, in percent. "
            "Wider = stress concentrated at distressed end. "
            "Column renamed ccc_bb_spread_pct (was ccc_bb_spread in v1/v2) per DATA-D12."
        ),
        "source_reference": "derived: ccc_hy_oas - bb_hy_oas",
        "refresh_ttl_days": 1
    },
    "hy_ig_realized_vol_21d": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "HY-IG Spread Realized Vol (21d, decimal)",
        "direction": "lower_is_better",
        "description": (
            "21-day rolling realized volatility of daily hy_ig_spread_pct changes, "
            "expressed as a decimal (0.30 = 30% annualized)."
        ),
        "source_reference": "derived: std(diff(spread), 21) * sqrt(252)",
        "refresh_ttl_days": 1
    },
    "vix_term_structure": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "VIX Term Structure",
        "direction": "higher_is_better",
        "description": (
            "VIX3M minus VIX (index-level difference). Positive = normal contango "
            "(calm); negative = backwardation (acute stress)."
        ),
        "source_reference": "derived: vix3m - vix",
        "refresh_ttl_days": 1
    },
    "yield_spread_10y3m_pct": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "10Y-3M Yield Spread (%)",
        "direction": "higher_is_better",
        "description": (
            "US Treasury 10Y yield minus 3M T-bill yield, in percentage points. "
            "Inversion (negative) is a classic recession signal. "
            "Column suffixed _pct per DATA-D12 (was yield_spread_10y3m in v1/v2)."
        ),
        "source_reference": "derived: dgs10 - dtb3",
        "refresh_ttl_days": 1
    },
    "yield_spread_10y2y_pct": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "10Y-2Y Yield Spread (%)",
        "direction": "higher_is_better",
        "description": (
            "US Treasury 10Y minus 2Y yield, in percentage points. "
            "Column suffixed _pct per DATA-D12 (was yield_spread_10y2y in v1/v2)."
        ),
        "source_reference": "derived: dgs10 - dgs2",
        "refresh_ttl_days": 1
    },
    "bank_smallcap_ratio": {
        "dtype": "float64",
        "unit": "ratio",
        "display_name": "KBE/IWM Ratio",
        "direction": "higher_is_better",
        "description": (
            "Banks (KBE) divided by small-caps (IWM) — relative-strength gauge for "
            "banking health. Dimensionless ratio."
        ),
        "source_reference": "derived: kbe / iwm",
        "refresh_ttl_days": 1
    },
    "nfci_momentum_13w": {
        "dtype": "float64",
        "unit": "index",
        "display_name": "NFCI 13-Week Momentum",
        "direction": "lower_is_better",
        "description": (
            "13-week (~1 quarter) change in NFCI. Rising = conditions tightening faster."
        ),
        "source_reference": "derived: nfci[t] - nfci[t-65bdays]",
        "refresh_ttl_days": 7
    },
    "bbb_ig_spread_pct": {
        "dtype": "float64",
        "unit": "percent",
        "display_name": "BBB-IG Spread (%)",
        "direction": "lower_is_better",
        "description": (
            "BBB OAS minus total IG OAS, in percent. Within-IG quality-tier stress gauge. "
            "Column suffixed _pct per DATA-D12 (was bbb_ig_spread in v1/v2)."
        ),
        "source_reference": "derived: bbb_oas - ig_oas",
        "refresh_ttl_days": 1
    },
    "spy_ret": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY Daily Return (decimal)",
        "direction": "higher_is_better",
        "description": "Simple 1-day total return of SPY as decimal (0.01 = 1%).",
        "source_reference": "derived: spy[t] / spy[t-1] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_1d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 1-Day Forward Return",
        "direction": "higher_is_better",
        "description": "Forward-looking 1-trading-day total return of SPY (decimal).",
        "source_reference": "derived: spy[t+1] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_5d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 5-Day Forward Return",
        "direction": "higher_is_better",
        "description": "Forward-looking 5-trading-day total return of SPY (decimal).",
        "source_reference": "derived: spy[t+5] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_21d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 21-Day Forward Return",
        "direction": "higher_is_better",
        "description": "Forward-looking 21-trading-day (~1M) total return of SPY (decimal).",
        "source_reference": "derived: spy[t+21] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_63d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 63-Day Forward Return",
        "direction": "higher_is_better",
        "description": (
            "Forward-looking 63-trading-day (~3M) total return of SPY (decimal). "
            "Primary dependent variable for predictive regressions."
        ),
        "source_reference": "derived: spy[t+63] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_126d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 126-Day Forward Return",
        "direction": "higher_is_better",
        "description": "Forward-looking 126-trading-day (~6M) total return of SPY (decimal).",
        "source_reference": "derived: spy[t+126] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
    "spy_fwd_252d": {
        "dtype": "float64",
        "unit": "decimal_return",
        "display_name": "SPY 252-Day Forward Return",
        "direction": "higher_is_better",
        "description": "Forward-looking 252-trading-day (~1y) total return of SPY (decimal).",
        "source_reference": "derived: spy[t+252] / spy[t] - 1",
        "refresh_ttl_days": 1
    },
}


def write_schema(df: pd.DataFrame, path: str) -> None:
    """Write DATA-D5 schema sidecar. Only includes columns present in df."""
    present = {c: SCHEMA_COLUMNS[c] for c in df.columns if c in SCHEMA_COLUMNS}
    sidecar = {
        "pair_id": PAIR_ID,
        "parquet_path": PARQUET_PATH,
        "schema_version": "1.0.0",
        "generated_at": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "columns": present,
    }
    with open(path, "w") as fh:
        json.dump(sidecar, fh, indent=2)
    print(f"  Schema sidecar written: {path}  ({len(present)} columns)")


# ─────────────────────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────────────────────

def main():
    t0 = time.time()
    print(f"\n{'='*60}")
    print(f"  {INDICATOR} → {TARGET}")
    print(f"  Pair ID: {PAIR_ID}")
    print(f"  Wave 10G.4A — Data Stage  |  {END_DATE}")
    print(f"{'='*60}")

    # Stage 1: fetch
    series = stage_data()

    # Stage 2: derive
    df = stage_derived(series)

    # DATA-D12: pre-save column-suffix linter
    print(f"\n  [DATA-D12] Running column-suffix linter …")
    violations = lint_column_suffixes(df)
    if violations:
        for v in violations:
            print(f"  [DATA-D12 VIOLATION] {v}")
        raise RuntimeError(
            f"DATA-D12 pre-save linter found {len(violations)} violation(s). "
            "Rename columns before saving. Pipeline halted."
        )
    else:
        print(f"  [DATA-D12] PASS — all {len(df.columns)} columns conform.")

    # Save parquet
    df.to_parquet(PARQUET_PATH, engine="pyarrow")
    size_kb = os.path.getsize(PARQUET_PATH) / 1024
    print(f"\n  Saved master parquet : {PARQUET_PATH}")
    print(f"  Rows: {len(df)}  Cols: {df.shape[1]}  Size: {size_kb:.1f} KB")
    print(f"  Date range: {df.index.min().date()} to {df.index.max().date()}")

    # DATA-D5: schema sidecar
    write_schema(df, SCHEMA_PATH)

    elapsed = time.time() - t0
    print(f"\n  Data stage complete in {elapsed:.1f}s")
    print(f"  Parquet : {PARQUET_PATH}")
    print(f"  Schema  : {SCHEMA_PATH}")
    return df


if __name__ == "__main__":
    main()
