"""
VIZ-CP1 Cross-Period Consistency Charts — Retro-Apply for all 10 pairs
Generated by Viz Vera | 2026-04-24
Rules applied: VIZ-CP1
"""

import json
import os
import warnings
from datetime import datetime
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

warnings.filterwarnings("ignore")

# ── Constants ─────────────────────────────────────────────────────────────────
BASE = Path("/workspaces/aig-rlic-plus")


def load_episodes(pair_id: str) -> list:
    """Load pair-class-specific stress episodes from the canonical registry.

    Reads docs/schemas/episode_registry.json, looks up indicator_category from
    results/{pair_id}/interpretation_metadata.json, and returns the matching
    episode list. Falls back to _fallback if the category is absent or unknown.
    The episode dict has keys: slug, label, start, end, rationale.
    Use for any episode-dependent chart logic (e.g., sub-period bar chart labels).
    """
    registry = json.loads((BASE / "docs/schemas/episode_registry.json").read_text())
    interp_path = BASE / f"results/{pair_id}/interpretation_metadata.json"
    category = "unknown"
    if interp_path.exists():
        interp = json.loads(interp_path.read_text())
        category = interp.get("indicator_category", interp.get("indicator_type", "unknown"))
    return registry.get(category, registry["_fallback"])
RESULTS = BASE / "results"
CHARTS = BASE / "output" / "charts"
GENERATED_AT = "2026-04-24"

PAIRS = [
    "dff_ted_spy",
    "hy_ig_spy",
    "hy_ig_v2_spy",
    "indpro_spy",
    "indpro_xlp",
    "permit_spy",
    "sofr_ted_spy",
    "ted_spliced_spy",
    "umcsent_xlv",
    "vix_vix3m_spy",
]

# NBER recessions
NBER_SHADING = "rgba(150,120,120,0.22)"
RECESSIONS = [
    ("2001-03-01", "2001-11-01"),
    ("2007-12-01", "2009-06-01"),
    ("2020-02-01", "2020-04-01"),
]


def add_nber_shading(fig, x_min, x_max, xref="x"):
    for s, e in RECESSIONS:
        s_dt, e_dt = pd.Timestamp(s), pd.Timestamp(e)
        if e_dt < x_min or s_dt > x_max:
            continue
        fig.add_shape(
            type="rect",
            x0=max(s_dt, x_min).isoformat(),
            x1=min(e_dt, x_max).isoformat(),
            y0=0,
            y1=1,
            xref=xref,
            yref="paper",
            fillcolor=NBER_SHADING,
            layer="below",
            line_width=0,
        )


def save_chart(fig, out_dir: Path, chart_name: str, pair_id: str, chart_type: str):
    out_dir.mkdir(parents=True, exist_ok=True)
    chart_path = out_dir / f"{chart_name}.json"
    meta_path = out_dir / f"{chart_name}_meta.json"

    chart_path.write_text(fig.to_json())

    meta = {
        "pair_id": pair_id,
        "chart_type": chart_type,
        "rules_applied": ["VIZ-CP1"],
        "generated_at": GENERATED_AT,
    }
    meta_path.write_text(json.dumps(meta, indent=2))


# ── Chart builders ─────────────────────────────────────────────────────────────

def build_subperiod_sharpe(df: pd.DataFrame, pair_id: str) -> go.Figure:
    """Horizontal bar chart of Sharpe by market episode."""
    # Build display labels: append (IS) for in-sample periods
    labels = []
    for _, row in df.iterrows():
        label = row["period_name"]
        if not row["is_oos"]:
            label += " (IS)"
        labels.append(label)

    sharpes = df["sharpe"].tolist()
    colors = ["rgba(0,158,115,0.85)" if s > 0 else "rgba(213,94,0,0.85)" for s in sharpes]

    fig = go.Figure()

    fig.add_trace(
        go.Bar(
            x=sharpes,
            y=labels,
            orientation="h",
            marker_color=colors,
            name="Sharpe Ratio",
            text=[f"{s:.2f}" for s in sharpes],
            textposition="outside",
        )
    )

    # Reference line at x=0
    fig.add_vline(x=0, line_dash="solid", line_color="black", line_width=1.5)

    fig.update_layout(
        title=dict(text="Strategy Performance Across Market Episodes", font=dict(size=15)),
        xaxis_title="Sharpe Ratio",
        yaxis_title="",
        width=700,
        height=450,
        margin=dict(l=160, r=80, t=60, b=80),
        annotations=[
            dict(
                text=(
                    "Sharpe ratios computed using simplified sign(signal)×return strategy. "
                    "IS = In-Sample period."
                ),
                xref="paper",
                yref="paper",
                x=0,
                y=-0.18,
                showarrow=False,
                font=dict(size=10, color="grey"),
                align="left",
            )
        ],
        plot_bgcolor="white",
        paper_bgcolor="white",
    )
    fig.update_xaxes(zeroline=False, gridcolor="rgba(200,200,200,0.4)")
    fig.update_yaxes(autorange="reversed")

    return fig


def build_rolling_correlation(df: pd.DataFrame, pair_id: str) -> go.Figure:
    """Rolling 24M signal–return correlation line chart with NBER shading."""
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").dropna(subset=["rolling_corr_24m"])
    x_min, x_max = df["date"].min(), df["date"].max()

    fig = go.Figure()

    # ±0.1 corridor fill
    fig.add_trace(
        go.Scatter(
            x=df["date"].tolist() + df["date"].tolist()[::-1],
            y=[0.1] * len(df) + [-0.1] * len(df),
            fill="toself",
            fillcolor="rgba(200,200,200,0.25)",
            line=dict(width=0),
            showlegend=True,
            name="±0.1 corridor",
            hoverinfo="skip",
        )
    )

    # Zero line
    fig.add_hline(y=0, line_dash="dash", line_color="grey", line_width=1)

    # Main trace
    fig.add_trace(
        go.Scatter(
            x=df["date"],
            y=df["rolling_corr_24m"],
            mode="lines",
            line=dict(color="rgba(0,114,178,0.85)", width=2),
            name="Rolling 24M Correlation",
        )
    )

    add_nber_shading(fig, x_min, x_max)

    fig.update_layout(
        title=dict(text="Rolling 24-Month Signal–Return Correlation", font=dict(size=15)),
        xaxis_title="Date",
        yaxis_title="Pearson Correlation",
        width=900,
        height=400,
        margin=dict(l=70, r=40, t=60, b=80),
        annotations=[
            dict(
                text=(
                    "Pearson correlation between signal and forward return. "
                    "Positive = signal leads returns in expected direction."
                ),
                xref="paper",
                yref="paper",
                x=0,
                y=-0.22,
                showarrow=False,
                font=dict(size=10, color="grey"),
                align="left",
            )
        ],
        plot_bgcolor="white",
        paper_bgcolor="white",
        legend=dict(orientation="h", y=-0.35),
    )
    fig.update_xaxes(gridcolor="rgba(200,200,200,0.4)")
    fig.update_yaxes(gridcolor="rgba(200,200,200,0.4)")

    return fig


def build_structural_break(
    corr_df: pd.DataFrame, sb: dict, pair_id: str
) -> go.Figure:
    """Structural break chart: rolling correlation background + break annotation."""
    corr_df["date"] = pd.to_datetime(corr_df["date"])
    corr_df = corr_df.sort_values("date").dropna(subset=["rolling_corr_24m"])
    x_min, x_max = corr_df["date"].min(), corr_df["date"].max()

    breakpoint = pd.Timestamp(sb["breakpoint_date"])
    f_stat = sb["max_f_stat"]
    p_val = sb["p_value"]
    conclusion = sb.get("conclusion", "")

    fig = go.Figure()

    # Zero line
    fig.add_hline(y=0, line_dash="dash", line_color="grey", line_width=1)

    # Background correlation trace
    fig.add_trace(
        go.Scatter(
            x=corr_df["date"],
            y=corr_df["rolling_corr_24m"],
            mode="lines",
            line=dict(color="rgba(0,114,178,0.65)", width=1.5),
            name="Rolling 24M Correlation",
        )
    )

    add_nber_shading(fig, x_min, x_max)

    # Vertical break line
    if x_min <= breakpoint <= x_max:
        fig.add_vline(
            x=breakpoint.timestamp() * 1000,  # ms for plotly
            line_dash="dot",
            line_color="rgba(213,94,0,0.9)",
            line_width=2,
            annotation_text="Structural Break",
            annotation_position="top right",
            annotation_font=dict(size=10, color="rgba(213,94,0,1)"),
        )

    # Text annotation for test result
    p_str = f"p={p_val:.3f}" if p_val is not None else "p=N/A"
    annot_text = f"Quandt-Andrews test: F={f_stat:.2f}, {p_str}"

    fig.update_layout(
        title=dict(
            text=f"Structural Break Analysis — {pair_id}", font=dict(size=15)
        ),
        xaxis_title="Date",
        yaxis_title="Rolling 24M Correlation",
        width=900,
        height=400,
        margin=dict(l=70, r=40, t=60, b=100),
        annotations=[
            dict(
                text=annot_text,
                xref="paper",
                yref="paper",
                x=0,
                y=-0.22,
                showarrow=False,
                font=dict(size=10, color="rgba(213,94,0,1)"),
                align="left",
            )
        ],
        plot_bgcolor="white",
        paper_bgcolor="white",
    )
    fig.update_xaxes(gridcolor="rgba(200,200,200,0.4)")
    fig.update_yaxes(gridcolor="rgba(200,200,200,0.4)")

    return fig


def build_rolling_sharpe_cp(df: pd.DataFrame, pair_id: str) -> go.Figure:
    """Rolling 24M strategy Sharpe with positive/negative shading and NBER."""
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").dropna(subset=["rolling_sharpe_24m"])
    x_min, x_max = df["date"].min(), df["date"].max()
    y = df["rolling_sharpe_24m"]

    fig = go.Figure()

    # Positive fill (above zero)
    pos_y = y.clip(lower=0)
    fig.add_trace(
        go.Scatter(
            x=df["date"],
            y=pos_y,
            mode="none",
            fill="tozeroy",
            fillcolor="rgba(0,158,115,0.18)",
            showlegend=False,
            hoverinfo="skip",
        )
    )

    # Negative fill (below zero)
    neg_y = y.clip(upper=0)
    fig.add_trace(
        go.Scatter(
            x=df["date"],
            y=neg_y,
            mode="none",
            fill="tozeroy",
            fillcolor="rgba(213,94,0,0.18)",
            showlegend=False,
            hoverinfo="skip",
        )
    )

    # Zero line
    fig.add_hline(y=0, line_dash="dash", line_color="grey", line_width=1)

    # Main trace
    fig.add_trace(
        go.Scatter(
            x=df["date"],
            y=y,
            mode="lines",
            line=dict(color="rgba(0,158,115,0.85)", width=2),
            name="Rolling 24M Sharpe",
        )
    )

    add_nber_shading(fig, x_min, x_max)

    fig.update_layout(
        title=dict(text="Rolling 24-Month Strategy Sharpe Ratio", font=dict(size=15)),
        xaxis_title="Date",
        yaxis_title="Sharpe Ratio (annualized)",
        width=900,
        height=400,
        margin=dict(l=70, r=40, t=60, b=80),
        annotations=[
            dict(
                text="Rolling annualized Sharpe ratio of the winner strategy.",
                xref="paper",
                yref="paper",
                x=0,
                y=-0.22,
                showarrow=False,
                font=dict(size=10, color="grey"),
                align="left",
            )
        ],
        plot_bgcolor="white",
        paper_bgcolor="white",
    )
    fig.update_xaxes(gridcolor="rgba(200,200,200,0.4)")
    fig.update_yaxes(gridcolor="rgba(200,200,200,0.4)")

    return fig


def build_rolling_granger(df: pd.DataFrame, pair_id: str) -> go.Figure:
    """Rolling 24M Granger F-stat with significance threshold and p-value on right axis."""
    df["date"] = pd.to_datetime(df["date"])
    df = df.sort_values("date").dropna(subset=["granger_f_24m"])
    x_min, x_max = df["date"].min(), df["date"].max()

    has_pval = "p_value_24m" in df.columns

    fig = make_subplots(specs=[[{"secondary_y": True}]])

    # Main F-stat trace
    fig.add_trace(
        go.Scatter(
            x=df["date"],
            y=df["granger_f_24m"],
            mode="lines",
            line=dict(color="rgba(230,159,0,0.85)", width=2),
            name="Granger F-stat (24M)",
        ),
        secondary_y=False,
    )

    # Significance threshold line at F=3.84
    fig.add_hline(
        y=3.84,
        line_dash="dash",
        line_color="rgba(204,0,0,0.75)",
        line_width=1.5,
        annotation_text="5% significance (F=3.84)",
        annotation_position="top left",
        annotation_font=dict(size=10, color="rgba(204,0,0,0.9)"),
        secondary_y=False,
    )

    # p-value on right axis
    if has_pval:
        fig.add_trace(
            go.Scatter(
                x=df["date"],
                y=df["p_value_24m"],
                mode="lines",
                line=dict(color="rgba(120,120,120,0.65)", width=1.5, dash="dash"),
                name="p-value (right axis)",
            ),
            secondary_y=True,
        )

    add_nber_shading(fig, x_min, x_max, xref="x")

    fig.update_layout(
        title=dict(
            text="Rolling Granger Causality: Signal → Forward Return",
            font=dict(size=15),
        ),
        width=900,
        height=400,
        margin=dict(l=70, r=80, t=60, b=80),
        annotations=[
            dict(
                text=(
                    "Rolling 24-month Granger F-statistic. "
                    "Dashed line = 5% significance threshold."
                ),
                xref="paper",
                yref="paper",
                x=0,
                y=-0.22,
                showarrow=False,
                font=dict(size=10, color="grey"),
                align="left",
            )
        ],
        plot_bgcolor="white",
        paper_bgcolor="white",
        legend=dict(orientation="h", y=-0.35),
    )
    fig.update_xaxes(title_text="Date", gridcolor="rgba(200,200,200,0.4)")
    fig.update_yaxes(
        title_text="Granger F-statistic",
        gridcolor="rgba(200,200,200,0.4)",
        secondary_y=False,
    )
    if has_pval:
        fig.update_yaxes(
            title_text="p-value",
            secondary_y=True,
            range=[0, 1],
            gridcolor="rgba(0,0,0,0)",
        )

    return fig


# ── Main loop ─────────────────────────────────────────────────────────────────

CHART_NAMES = [
    "subperiod_sharpe",
    "rolling_correlation",
    "structural_break",
    "rolling_sharpe_cp",
    "rolling_granger",
]

results_table = []

for pair_id in PAIRS:
    res_dir = RESULTS / pair_id
    out_dir = CHARTS / pair_id / "plotly"
    row = {"pair": pair_id}

    # ── 1. subperiod_sharpe ────────────────────────────────────────────────
    chart = "subperiod_sharpe"
    fp = res_dir / "subperiod_sharpe.csv"
    try:
        df = pd.read_csv(fp)
        fig = build_subperiod_sharpe(df, pair_id)
        save_chart(fig, out_dir, chart, pair_id, "horizontal_bar")
        row[chart] = "DONE"
    except FileNotFoundError:
        print(f"  SKIP {pair_id}/{chart}: file not found")
        row[chart] = "SKIP"
    except Exception as exc:
        print(f"  ERROR {pair_id}/{chart}: {exc}")
        row[chart] = "ERROR"

    # ── 2. rolling_correlation ─────────────────────────────────────────────
    chart = "rolling_correlation"
    fp = res_dir / f"rolling_correlation_{pair_id}.csv"
    corr_df_cache = None
    try:
        corr_df_cache = pd.read_csv(fp)
        fig = build_rolling_correlation(corr_df_cache.copy(), pair_id)
        save_chart(fig, out_dir, chart, pair_id, "time_series_line")
        row[chart] = "DONE"
    except FileNotFoundError:
        print(f"  SKIP {pair_id}/{chart}: file not found")
        row[chart] = "SKIP"
    except Exception as exc:
        print(f"  ERROR {pair_id}/{chart}: {exc}")
        row[chart] = "ERROR"

    # ── 3. structural_break ────────────────────────────────────────────────
    chart = "structural_break"
    fp_sb = res_dir / f"structural_break_{pair_id}.json"
    try:
        sb = json.loads(fp_sb.read_text())
        if corr_df_cache is None:
            # Try to reload correlation file
            corr_fp = res_dir / f"rolling_correlation_{pair_id}.csv"
            corr_df_cache = pd.read_csv(corr_fp)
        fig = build_structural_break(corr_df_cache.copy(), sb, pair_id)
        save_chart(fig, out_dir, chart, pair_id, "event_annotation")
        row[chart] = "DONE"
    except FileNotFoundError:
        print(f"  SKIP {pair_id}/{chart}: file not found")
        row[chart] = "SKIP"
    except Exception as exc:
        print(f"  ERROR {pair_id}/{chart}: {exc}")
        row[chart] = "ERROR"

    # ── 4. rolling_sharpe_cp ───────────────────────────────────────────────
    chart = "rolling_sharpe_cp"
    fp = res_dir / f"rolling_sharpe_{pair_id}.csv"
    try:
        df = pd.read_csv(fp)
        fig = build_rolling_sharpe_cp(df, pair_id)
        save_chart(fig, out_dir, chart, pair_id, "time_series_line")
        row[chart] = "DONE"
    except FileNotFoundError:
        print(f"  SKIP {pair_id}/{chart}: file not found")
        row[chart] = "SKIP"
    except Exception as exc:
        print(f"  ERROR {pair_id}/{chart}: {exc}")
        row[chart] = "ERROR"

    # ── 5. rolling_granger ─────────────────────────────────────────────────
    chart = "rolling_granger"
    fp = res_dir / f"rolling_granger_{pair_id}.csv"
    try:
        df = pd.read_csv(fp)
        fig = build_rolling_granger(df, pair_id)
        save_chart(fig, out_dir, chart, pair_id, "time_series_dual_axis")
        row[chart] = "DONE"
    except FileNotFoundError:
        print(f"  SKIP {pair_id}/{chart}: file not found")
        row[chart] = "SKIP"
    except Exception as exc:
        print(f"  ERROR {pair_id}/{chart}: {exc}")
        row[chart] = "ERROR"

    results_table.append(row)
    print(f"[{pair_id}] " + " | ".join(f"{k}:{v}" for k, v in row.items() if k != "pair"))

# ── Summary table ──────────────────────────────────────────────────────────────
print("\n" + "=" * 100)
print(f"{'PAIR':<22} {'subperiod_sharpe':<20} {'rolling_corr':<18} {'struct_break':<16} {'rolling_sharpe_cp':<20} {'rolling_granger'}")
print("-" * 100)
for row in results_table:
    print(
        f"{row['pair']:<22} "
        f"{row.get('subperiod_sharpe','?'):<20} "
        f"{row.get('rolling_correlation','?'):<18} "
        f"{row.get('structural_break','?'):<16} "
        f"{row.get('rolling_sharpe_cp','?'):<20} "
        f"{row.get('rolling_granger','?')}"
    )
print("=" * 100)
print("\nNBER shading: APPLIED to rolling_correlation, structural_break, rolling_sharpe_cp, rolling_granger")
print("Recessions shaded: 2001-03–2001-11, 2007-12–2009-06, 2020-02–2020-04")
print(f"Generated at: {GENERATED_AT}")
